import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {validateCatalog,validatePublicCatalog} from '../src/catalog.ts';import {syncCatalog,safetyValid} from '../src/sync.ts';
import {catalog,safety,now,input} from './fixtures.ts';import {calculate} from '../src/calculate.ts';import type {Bootstrap,CacheState} from '../../../contracts/types.ts';
const hash=async(s:string)=>createHash('sha256').update(s).digest('hex');
function boot():Bootstrap{const text=JSON.stringify(catalog);return {schemaVersion:1,semanticsVersion:1,releaseId:catalog.releaseId,catalogPath:'/v1/catalog/'+catalog.releaseId,sha256:createHash('sha256').update(text).digest('hex'),sizeBytes:Buffer.byteLength(text),safety:{...safety}};}
test('Schema와 참조/중복/기간/의미/비율 검사',()=>{for(const value of [{}, {...catalog,schemaVersion:2},{...catalog,rules:[{...catalog.rules[0],productId:'missing'}]},{...catalog,rules:[catalog.rules[0],catalog.rules[0]]},{...catalog,rules:[{...catalog.rules[0],calculation:{...catalog.rules[0].calculation,value:10001}}]}])assert.throws(()=>validateCatalog(value));assert.equal(validateCatalog(catalog).releaseId,'fixture-v1');});
test('이용권·실제 독립검수 없는 자료/fixture 공개 차단, empty 허용',()=>{assert.throws(()=>validatePublicCatalog(catalog,now));assert.doesNotThrow(()=>validatePublicCatalog({...catalog,brands:[],products:[],sources:[],places:[],rules:[],combinations:[]},now));const x=structuredClone(catalog);x.rules.forEach(r=>r.origin='CATALOG');assert.throws(()=>validatePublicCatalog(x,now));});
test('안전24시간과 기기시계회귀/서버시각불확실',()=>{assert.equal(safetyValid(safety,now+86400000),false);assert.equal(safetyValid(safety,now-1),false);assert.equal(safetyValid(null,now),false);assert.equal(safetyValid({...safety,serverTime:'2026-08-01T00:00:00Z'},now),false);});
test('새 차단/OFF는 다운로드 실패보다 먼저 영속 적용',async()=>{let saved=false;const b=boot();b.safety.revision=2;b.safety.blockedRuleIds=['m'];b.safety.flags.catalog=false;const state:CacheState={catalog,safety};const next=await syncCatalog(state,b,async()=>{assert.equal(saved,true);throw Error('network');},hash,async(s)=>{saved=true;assert.equal(s.flags.catalog,false);},async()=>assert.fail('must retain old catalog'),now);assert.equal(next.catalog,catalog);assert.deepEqual(next.safety?.blockedRuleIds,['m']);assert.equal(next.safety?.revision,2);});
test('검증실패/오래된 safety/bootstrap은 확인시각 연장·캐시교체 안함',async()=>{const b=boot();b.safety.revision=0;await assert.rejects(syncCatalog({catalog,safety},b,async()=>JSON.stringify(catalog),hash,async()=>{},async()=>{},now+1000));});
test('해시·크기·release 불일치 실패는 카탈로그 보존',async()=>{const b=boot();let count=0;const next=await syncCatalog({catalog,safety},b,async()=>JSON.stringify({...catalog,releaseId:'wrong'}),hash,async()=>{},async()=>{count++;},now);assert.equal(count,0);assert.equal(next.catalog,catalog);});
test('롤백 후 기존 차단 overlay 유지',async()=>{const old={...safety,blockedRuleIds:['m']};const b=boot();b.safety.revision=2;const next=await syncCatalog({catalog,safety:old},b,async()=>JSON.stringify(catalog),hash,async()=>{},async()=>{},now);assert.deepEqual(next.safety?.blockedRuleIds,['m']);});
test('공개 규칙은 원문·권리·안전 중 가장 빠른 만료를 준수',()=>{const x=input();x.mode='PUBLIC';x.catalog.rules.forEach(r=>{r.origin='CATALOG';r.review={author:'a',reviewer:'b',method:'HUMAN_ORIGINAL',reviewedAt:new Date(now).toISOString(),evidenceRef:'permission-test',goldenTests:['golden']};});for(const source of x.catalog.sources)for(const key of ['display','transform','iosDistribution','androidDistribution','offlineCache','update','revoke'] as const)source.rights[key]=true;x.catalog.sources[0].freshUntil=new Date(now).toISOString();assert.equal(calculate(x).best,null);});
test('검증한 empty 카탈로그만 성공 원자교체',async()=>{const empty={...catalog,releaseId:'empty-v2',brands:[],products:[],sources:[],places:[],rules:[],combinations:[]};const text=JSON.stringify(empty);const b=boot();b.releaseId=empty.releaseId;b.catalogPath='/v1/catalog/'+empty.releaseId;b.sha256=await hash(text);b.sizeBytes=Buffer.byteLength(text);let applied=false;const next=await syncCatalog({catalog,safety},b,async()=>text,hash,async()=>{},async(c)=>{applied=true;assert.equal(c.releaseId,'empty-v2');},now);assert.equal(applied,true);assert.equal(next.catalog?.releaseId,'empty-v2');});
test('형식 잘못된 safety flags/id는 새 정상확인으로 저장 금지',async()=>{const b=boot();(b.safety as any).flags={};await assert.rejects(syncCatalog({catalog,safety},b,async()=>'',hash,async()=>{},async()=>{},now));});
test('유효한 bootstrap 뒤 파일 실패도 마지막 정상 확인 기한을 연장하지 않음',async()=>{const later=now+23*3600000;const b=boot();b.safety.serverTime=new Date(later).toISOString();b.safety.revision=2;b.safety.blockedRuleIds=['m'];const next=await syncCatalog({catalog,safety},b,async()=>{throw Error('network');},hash,async()=>{},async()=>{},later);assert.equal(next.safety?.receivedAt,safety.receivedAt);assert.equal(safetyValid(next.safety,now+25*3600000),false);assert.deepEqual(next.safety?.blockedRuleIds,['m']);});
test('카탈로그 호환 불가에도 형식이 유효한 새 차단과 OFF는 먼저 저장',async()=>{const b=boot();(b as any).schemaVersion=2;b.safety.revision=2;b.safety.blockedRuleIds=['m'];b.safety.flags.catalog=false;let saved=false;const next=await syncCatalog({catalog,safety},b,async()=>assert.fail('incompatible download'),hash,async(s)=>{saved=true;assert.equal(s.flags.catalog,false);},async()=>{},now);assert.equal(saved,true);assert.equal(next.safety?.flags.catalog,false);});
test('JavaScript에서 지원하지 않는 윤초 날짜는 만료 검사 전에 거절',()=>{const x=structuredClone(catalog);x.sources[0].freshUntil='2026-09-30T23:59:60Z';x.sources[0].rightsUntil='2026-09-30T01:00:00Z';assert.throws(()=>validateCatalog(x));});
test('파일 실패는 이전 OFF를 ON으로 바꾸지 않음',async()=>{const old={...safety,flags:{...safety.flags,catalog:false}};const b=boot();const next=await syncCatalog({catalog,safety:old},b,async()=>{throw Error('network');},hash,async(s)=>assert.equal(s.flags.catalog,false),async()=>{},now);assert.equal(next.safety?.flags.catalog,false);});
