import React,{useEffect,useMemo,useState,useRef} from 'react';
import {AccessibilityInfo,AppState,Image,KeyboardAvoidingView,Linking,Platform,Pressable,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,TextInput,View} from 'react-native';
import {calculate,distanceMeters,kstMonth,safetyValid,syncCatalog} from '../../packages/benefit-core/src/index.ts';
import type {CacheState,Catalog,Rule,RuleConditions,Truth,WalletItem} from '../../contracts/types.ts';
import empty from '../../contracts/empty-catalog.json';
import {conditionLabel,emptyLocal,parseWon,personalCatalog,reasonText,unknownConditions,updateWallet,submitReportSafely,clearDeviceBeforeRemoteReport,type ReportReceipt,type LocalData} from './src/model.ts';
import {apiBase,deleteDeviceData,digest,foregroundPosition,id,initializeStorage,loadCache,loadLocal,request,saveCatalog,saveLocal,saveSafety,setNativeCatalog,startPilot,stopNative,pauseNative,runtimeTime,confirmRuntimeClock} from './src/native.ts';
import {clockAnchor} from './src/runtime-safety.ts';
const color={brand:'#086653',accent:'#DFF584',background:'#F6F8F3',text:'#192D26',muted:'#52635A',border:'#718077'};
const money=(value:number)=>value.toLocaleString('ko-KR')+'원';
const truthOptions=[{id:'TRUE',name:'충족'},{id:'FALSE',name:'미충족'},{id:'UNKNOWN',name:'모름'}];
function Button({label,onPress,secondary=false,danger=false,disabled=false}:{label:string;onPress:()=>void;secondary?:boolean;danger?:boolean;disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={[s.button,secondary&&s.secondary,danger&&s.danger,disabled&&{opacity:0.5}]}><Text style={[s.buttonText,secondary&&{color:color.brand}]}>{label}</Text></Pressable>;}
function Choices({label,options,value,onChange}:{label:string;options:{id:string;name:string}[];value:string;onChange:(value:string)=>void}){return <View style={s.field}><Text style={s.label}>{label}</Text><View style={s.choices}>{options.map(option=><Pressable key={option.id} accessibilityRole="radio" accessibilityLabel={`${label}, ${option.name}`} accessibilityState={{selected:value===option.id}} onPress={()=>onChange(option.id)} style={[s.choice,value===option.id&&s.selected]}><Text style={[s.body,value===option.id&&{color:'white'}]}>{option.name}</Text></Pressable>)}</View></View>;}
function Field({label,value,onChange,numeric=false,multiline=false,hint,maxLength=100}:{label:string;value:string;onChange:(value:string)=>void;numeric?:boolean;multiline?:boolean;hint?:string;maxLength?:number}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} keyboardType={numeric?'number-pad':'default'} autoCapitalize="none" multiline={multiline} maxLength={maxLength} style={[s.input,multiline&&{minHeight:112,textAlignVertical:'top'}]} />{hint&&<Text style={s.small}>{hint}</Text>}</View>;}
function Panel({title,children,tone='plain'}:{title:string;children?:React.ReactNode;tone?:'plain'|'warning'|'info'}){return <View style={[s.card,tone==='warning'&&{backgroundColor:'#FFF4D6'},tone==='info'&&{backgroundColor:'#EDF4FB'}]}><Text accessibilityRole="header" style={s.subtitle}>{title}</Text>{children}</View>;}
const description=(text:string)=><Text style={s.body}>{text}</Text>;
const newWallet=():WalletItem=>({id:id(),name:'',kind:'CARD',tier:'모름',productVersion:null});
export default function App(){
  const running=useRef(false),expired=useRef(true);
  const [wallNow,setWallNow]=useState(()=>runtimeTime().now),[pendingReceipt,setPendingReceipt]=useState<ReportReceipt|null>(null);
  const [tab,setTab]=useState('혜택'),[data,setData]=useState<LocalData>(emptyLocal),[loaded,setLoaded]=useState(false),[cache,setCache]=useState<CacheState>({catalog:null,safety:null});
  const [busy,setBusy]=useState(false),[message,setMessage]=useState('혜택 자료를 확인하고 있어요.'),[error,setError]=useState(''),[offline,setOffline]=useState(false),[mode,setMode]=useState<'PUBLIC'|'PERSONAL'|'DEMO'>('PUBLIC');
  const [demo,setDemo]=useState<Catalog|null>(null),[demoNow,setDemoNow]=useState(0),[demoConditions,setDemoConditions]=useState<Record<string,RuleConditions>>({});
  const [brand,setBrand]=useState(''),[place,setPlace]=useState(''),[channel,setChannel]=useState('OFFLINE'),[region,setRegion]=useState(''),[amount,setAmount]=useState(''),[eligible,setEligible]=useState(''),[selected,setSelected]=useState<string[]>([]),[showResult,setShowResult]=useState(false);
  const [wallet,setWallet]=useState<WalletItem|null>(null),[editingWallet,setEditingWallet]=useState(false),[rule,setRule]=useState<Rule|null>(null),[ruleValue,setRuleValue]=useState(''),[ruleCap,setRuleCap]=useState(''),[ruleMinimum,setRuleMinimum]=useState(''),[ruleSource,setRuleSource]=useState('');
  const [reportRule,setReportRule]=useState(''),[reportCategory,setReportCategory]=useState('CONDITION'),[reportMessage,setReportMessage]=useState(''),[reportOpen,setReportOpen]=useState(false),[deleteConfirm,setDeleteConfirm]=useState(false),[nearby,setNearby]=useState<{id:string;name:string;distance:number}[]>([]);
  const clockTrusted=runtimeTime().trusted;
  const now=mode==='DEMO'?demoNow:wallNow;
  const catalog=mode==='DEMO'?(demo??empty as Catalog):mode==='PERSONAL'?personalCatalog(data,now):(cache.catalog??empty as Catalog);
  const conditions=mode==='DEMO'?demoConditions:data.conditions;
  const visibleRules=catalog.rules.filter(r=>r.brandId===brand&&selected.includes(r.productId));
  const persist=async(next:LocalData)=>{await saveLocal(next);setData(next);};
  const run=async(action:()=>Promise<void>)=>{if(running.current)return;running.current=true;setBusy(true);setError('');try{await action();}catch(e){const text=e instanceof Error?e.message:'다시 시도해 주세요.';setError(text);AccessibilityInfo.announceForAccessibility(text);}finally{running.current=false;setBusy(false);}};
  async function refresh(current:CacheState=cache){
    try{
      const bootstrap=await (await request('/v1/bootstrap')).json();
      const attempt=clockAnchor(Date.now(),performance.now());let safetyWrites=0;
      const next=await syncCatalog(current,bootstrap,async path=>(await request(path)).text(),digest,async safety=>{await saveSafety(safety);safetyWrites++;setCache(previous=>({...previous,safety}));setNativeCatalog({...current,safety},data.wallet.map(w=>w.id));if(!safety.flags.catalog||!safety.flags[Platform.OS==='ios'?'iosBackground':'androidBackground'])await stopNative();},saveCatalog,attempt.wall);
      if(safetyWrites===2)confirmRuntimeClock(attempt,next.safety?.receivedAt??Number.NaN);
      setCache(next);setOffline(false);setWallNow(runtimeTime().now);setMessage(safetyWrites===2?'혜택 자료와 안전 상태를 확인했어요.':'안전 상태를 적용했어요. 자료 파일을 확인하지 못해 이전 자료를 유지해요.');return next;
    }catch(e){setOffline(true);setMessage('오프라인이에요. 마지막 정상 확인 시각은 연장하지 않아요.');throw e;}
  }
  useEffect(()=>{void run(async()=>{await initializeStorage();const local=await loadLocal();const saved=await loadCache();setData(local);setCache(saved);setLoaded(true);await refresh(saved);});},[]);
  useEffect(()=>{const timer=setInterval(()=>setWallNow(runtimeTime().now),1000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{const time=runtimeTime();const valid=time.trusted&&safetyValid(cache.safety,time.now)&&!!cache.safety?.flags.catalog;if(!valid&&!expired.current){pauseNative();setNearby([]);void stopNative().catch(e=>setError(e instanceof Error?e.message:'자동 작업 중지 실패'));}expired.current=!valid;},[wallNow,cache.safety]);
  useEffect(()=>{setNativeCatalog(cache,data.wallet.filter(w=>w.productVersion!==null).map(w=>w.id));},[cache,data.wallet]);
  useEffect(()=>{const subscription=AppState.addEventListener('change',state=>{if(state==='active'&&loaded)void run(async()=>{await refresh();});});return()=>subscription.remove();},[loaded,cache,data]);
  const calculation=useMemo(()=>{
    if(!showResult)return null;try{if(mode==='PUBLIC'&&!clockTrusted)throw Error('단말 시각 변경 또는 최신 시간 근거 확인이 필요해요. 자료 갱신 전 예상 계산을 보류해요.');const value=parseWon(amount);if(value===null||value<=0)throw Error('결제 금액을 확인해 주세요. 원 단위의 양의 정수를 입력해 주세요.');const eligibleValue=parseWon(eligible);
      const ids=mode==='PUBLIC'?selected.filter(pid=>data.wallet.some(w=>w.id===pid&&w.productVersion!==null)):selected;
      return {result:calculate({amountWon:value,...(eligibleValue===null?{}:{eligibleAmountWon:eligibleValue}),brandId:brand,placeId:place,channel,productIds:ids,catalog,conditions,safety:mode==='PUBLIC'?cache.safety??undefined:undefined,now,mode}),error:''};
    }catch(e){return {result:null,error:e instanceof Error?e.message:'입력을 확인해 주세요.'};}
  },[showResult,amount,eligible,brand,place,channel,selected,catalog,conditions,cache.safety,mode,now,data.wallet,clockTrusted]);
  async function changeMode(value:'PUBLIC'|'PERSONAL'|'DEMO'){
    if(value==='DEMO'){const fixture=await import('../../packages/benefit-core/test/fixtures.ts');setDemo(fixture.catalog);setDemoNow(fixture.now);setDemoConditions(unknownConditions(fixture.catalog.rules,fixture.now));}
    setMode(value);setBrand('');setPlace('');setRegion('');setSelected([]);setShowResult(false);setNearby([]);
  }
  function selectProduct(pid:string){const kind=catalog.products.find(p=>p.id===pid)?.kind;setSelected(prev=>prev.includes(pid)?prev.filter(p=>p!==pid):[...prev.filter(p=>catalog.products.find(x=>x.id===p)?.kind!==kind),pid]);}
  async function conditionChange(r:Rule,change:(c:RuleConditions)=>RuleConditions){const existing=conditions[r.id]??unknownConditions([r],now)[r.id];const c=existing.month===kstMonth(now)&&existing.ruleVersion===r.version?existing:unknownConditions([r],now)[r.id];const next={...conditions,[r.id]:change(c)};if(mode==='DEMO')setDemoConditions(next);else await persist({...data,conditions:next});}
  async function consent(key:'location'|'advertising'|'background',value:boolean){if(!value)pauseNative();const next={...data,consent:{...data.consent,[key]:value,updatedAt:new Date().toISOString()}};await persist(next);if(!value)await stopNative();setMessage(value?'선택한 동의를 단말에 저장했어요.':'동의를 철회하고 자동 작업·알림을 정리했어요.');}
  function openPersonalRule(existing?:Rule){const product=data.wallet[0];if(!product){setTab('내 지갑');setError('보유 수단 하나를 먼저 등록해 주세요.');return;}const current=existing??{id:id(),version:id(),origin:'USER_INPUT' as const,title:'',productId:product.id,brandId:'',sourceId:'personal',channels:['OFFLINE'],placeIds:[],startsAt:new Date().toISOString(),endsAt:new Date(Date.now()+30*86400000).toISOString(),status:'DRAFT' as const,requiredConditions:[product.kind==='CARD'?'spend':'tier','productVersion','eligibleItems'],remainingWonRequired:true,remainingUsesRequired:true,calculation:{kind:'PERCENT' as const,value:0,basis:'ORIGINAL' as const,minimumWon:0,minimumBasis:'ORIGINAL' as const,capWon:0,rounding:'FLOOR' as const,settlement:'INSTANT' as const},usageSteps:['공식 사용 조건과 순서를 결제 전에 확인'],exclusions:[]};setRule({...current});setRuleSource(data.ruleSourceUrl[current.id]??'');setRuleValue(String(current.calculation?.value??''));setRuleCap(String(current.calculation?.capWon??''));setRuleMinimum(String(current.calculation?.minimumWon??0));}
  const footer=<View style={s.nav}>{['혜택','내 지갑','설정'].map(name=><Pressable key={name} accessibilityRole="tab" accessibilityState={{selected:tab===name}} onPress={()=>setTab(name)} style={[s.navItem,tab===name&&{borderTopColor:color.brand,borderTopWidth:3}]}><Text style={[s.label,tab===name&&{color:color.brand}]}>{name}</Text></Pressable>)}</View>;
  return <SafeAreaView style={s.safe}><StatusBar barStyle="dark-content" backgroundColor={color.background}/><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.header}><Image source={require('../../assets/brand/symbol-1024.png')} accessible={false} style={{width:38,height:38}}/><View style={{flex:1}}><Text accessibilityRole="header" style={s.brand}>혜택패스</Text><Text style={s.small}>결제 전에, 확인한 조건만.</Text></View><Text style={s.badge}>검증판</Text></View>
    <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
      {Platform.OS==='web'&&<View style={s.banner}>{description('웹 미리보기 · 브라우저 저장소를 사용해요. 실제 지갑 정보 대신 시험 입력만 사용해 주세요.')}</View>}
      {mode==='DEMO'&&<View style={s.banner}>{description('개발용 가상 자료 · 실제 상품이 아님 · 계산 시각 2026년 9월 30일 12:00 고정')}</View>}
      {error&&<View accessibilityLiveRegion="polite" style={[s.banner,{backgroundColor:'#FFF1EF'}]}><Text style={[s.body,{color:'#B3261E'}]}>{error}</Text></View>}
      {pendingReceipt&&<Panel title="삭제 토큰을 저장하지 못한 서버 제보가 있어요." tone="warning"><Text style={s.body}>앱을 닫기 전에 아래 삭제 토큰을 따로 보관해 주세요. 토큰을 잃으면 서버 제보를 직접 삭제할 수 없어요.</Text><Text selectable style={s.small}>제보 ID: {pendingReceipt.id}{'\n'}삭제 토큰: {pendingReceipt.deleteToken}</Text><Button label="저장하지 못한 제보 서버 삭제 다시 시도" danger disabled={busy} onPress={()=>void run(async()=>{await request('/v1/reports/'+encodeURIComponent(pendingReceipt.id),{method:'DELETE',headers:{Authorization:'Bearer '+pendingReceipt.deleteToken}});setPendingReceipt(null);setMessage('저장하지 못한 서버 제보를 삭제했어요.');})}/><Button label="삭제 토큰 보호 저장 다시 시도" secondary disabled={busy} onPress={()=>void run(async()=>{await persist({...data,reports:[...data.reports,pendingReceipt]});setPendingReceipt(null);setMessage('제보 삭제 토큰을 보호 저장했어요.');})}/></Panel>}
      {!loaded&&<Panel title="단말 자료를 확인하고 있어요.">{description('보호 저장소와 최신 안전 상태를 확인합니다.')}{error&&<Button label="저장소 다시 확인" onPress={()=>void run(async()=>{await initializeStorage();setData(await loadLocal());setCache(await loadCache());setLoaded(true);})}/>}</Panel>}
      {tab==='혜택'&&<>
        <Text accessibilityRole="header" style={s.title}>결제 전 확인</Text><Text style={s.body}>가진 카드와 멤버십으로{ '\n' }확인할 조건을 하나씩.</Text>
        <Panel title={busy?'혜택 자료를 확인하고 있어요.':mode==='PUBLIC'&&!catalog.rules.length?'현재 공개 계산 자료가 없어요.':mode==='PERSONAL'?'직접 작성한 조건이에요.':'지원 범위'} tone="info">{description(mode==='PUBLIC'?'이용권과 실제 원문 검수를 확인한 자료부터 제공해요.':mode==='PERSONAL'?'사용자가 작성한 미검수 자료예요. 원문 검수 자료와 구분해 사용해 주세요.':'가상 조건으로 입력과 계산 흐름을 시험할 수 있어요.')}
          <Text style={s.small}>브랜드 {catalog.brands.length}개 · 상품 {catalog.products.length}개 · 규칙 {catalog.rules.length}개</Text><Text style={s.small}>{mode==='PUBLIC'?message:'이 자료는 공개 카탈로그와 섞이지 않아요.'}</Text>
          {mode==='PUBLIC'&&cache.safety&&<Text style={s.small}>서버 확인: {cache.safety.serverTime}{'\n'}이번 실행 안전 확인: {Number.isFinite(cache.safety.receivedAt)?new Date(cache.safety.receivedAt).toLocaleString('ko-KR'):'재조회 필요'}</Text>}
          {mode==='PUBLIC'&&(!clockTrusted||!safetyValid(cache.safety,now)||!cache.safety?.flags.catalog)&&<Text style={s.warning}>최신 상태 확인이 필요해요. 예상 계산과 자동 알림을 보류해요.</Text>}
          {mode==='PUBLIC'&&offline&&clockTrusted&&safetyValid(cache.safety,now)&&<Text style={s.small}>유효한 마지막 자료를 사용해요. 새 차단 여부는 아직 확인하지 못했어요. 안전 기한: {new Date(cache.safety!.receivedAt+86400000).toLocaleString('ko-KR')}</Text>}
          <Button label="자료 갱신" secondary disabled={busy} onPress={()=>void run(async()=>{await refresh();})}/>
        </Panel>
        <Choices label="확인할 자료" value={mode} options={[{id:'PUBLIC',name:'공개 자료'},{id:'PERSONAL',name:'내 직접 작성'},{id:'DEMO',name:'가상 예시 켜기'}]} onChange={value=>void run(()=>changeMode(value as typeof mode))}/>
        {mode==='PERSONAL'&&<Button label="조건 직접 작성" secondary disabled={!loaded||busy} onPress={()=>openPersonalRule()}/>}
        {!catalog.brands.length&&<Panel title="직접 작성과 지갑은 사용할 수 있어요.">{description('공개 지원 목록이 준비되면 브랜드·점포를 선택할 수 있어요. 지금은 보유 수단이나 내 조건을 단말에 등록해 주세요.')}<Button label="내 지갑 열기" onPress={()=>setTab('내 지갑')}/></Panel>}
        {!!catalog.brands.length&&<>
          {!!catalog.places.length&&<Choices label="생활권 직접 선택" options={[...new Set(catalog.places.map(p=>p.regionId))].map(id=>({id,name:id}))} value={region} onChange={value=>{setRegion(value);setPlace('');}}/>}
          <Choices label="브랜드 직접 선택" value={brand} options={catalog.brands} onChange={value=>{setBrand(value);setPlace('');setNearby([]);}}/>
          {!!brand&&<><Choices label="점포 직접 선택" value={place} options={[{id:'',name:'점포 모름'},...catalog.places.filter(p=>p.brandId===brand&&(!region||p.regionId===region)).map(p=>({id:p.id,name:p.name}))]} onChange={setPlace}/>
            <Choices label="결제 채널" value={channel} options={[{id:'OFFLINE',name:'매장 결제'},{id:'ONLINE',name:'온라인'},{id:'APP',name:'공식 앱'}]} onChange={setChannel}/>
            <Text style={s.subtitle}>이번 결제에 사용할 수단</Text><Text style={s.small}>한 카드와 최대 한 멤버십을 선택해요. 상품 버전 모름은 공개 계산에서 제외해요.</Text>
            {catalog.products.map(p=>{const owned=data.wallet.find(w=>w.id===p.id);return <Pressable key={p.id} accessibilityRole="checkbox" accessibilityState={{checked:selected.includes(p.id),disabled:mode!=='DEMO'&&!owned}} disabled={mode!=='DEMO'&&!owned} onPress={()=>selectProduct(p.id)} style={[s.choice,selected.includes(p.id)&&s.selected]}><Text style={[s.body,selected.includes(p.id)&&{color:'white'}]}>{selected.includes(p.id)?'✓ ':''}{p.name}{mode!=='DEMO'&&!owned?' · 지갑 등록 필요':''}</Text>{owned&&<Text style={[s.small,selected.includes(p.id)&&{color:'white'}]}>등급·유형: {owned.tier} · 상품 버전: {owned.productVersion??'모름'}</Text>}</Pressable>;})}
            <Field label="결제 금액 (원)" value={amount} onChange={setAmount} numeric hint="원 단위 양의 정수. 카드·계좌 정보는 입력하지 않아요."/>
            {visibleRules.some(r=>r.calculation?.basis==='ELIGIBLE'||r.calculation?.minimumBasis==='ELIGIBLE')&&<Field label="할인 대상 품목 금액 (원, 비우면 모름)" value={eligible} onChange={setEligible} numeric/>}
            {visibleRules.map(r=><Panel key={r.id} title={r.title}>
              <Text style={s.small}>{r.origin==='USER_INPUT'?'사용자 직접 작성 · 미검수':r.origin==='FIXTURE'?'가상 시험 자료':'자료 원문 검수 상태: '+r.status}</Text>
              {r.requiredConditions.map(key=><Choices key={key} label={conditionLabel(key)} value={conditions[r.id]?.values[key]?.value??'UNKNOWN'} options={truthOptions} onChange={value=>void run(()=>conditionChange(r,c=>({...c,values:{...c.values,[key]:{value:value as Truth,checkedAt:new Date(now).toISOString(),month:kstMonth(now),ruleVersion:r.version}}})))}/>)}
              {r.remainingWonRequired&&<Field label="이번 달 잔여 할인 한도 (원, 비우면 모름)" value={conditions[r.id]?.remainingWon?.toString()??''} numeric onChange={value=>void run(()=>conditionChange(r,c=>({...c,remainingWon:parseWon(value)})))}/>}
              {r.remainingUsesRequired&&<Field label="이번 달 잔여 이용 횟수 (비우면 모름)" value={conditions[r.id]?.remainingUses?.toString()??''} numeric onChange={value=>void run(()=>conditionChange(r,c=>({...c,remainingUses:parseWon(value)})))}/>}
              <Text style={s.small}>조건 기준월: {conditions[r.id]?.month??kstMonth(now)} · 혜택 버전 {r.version}{'\n'}월이나 버전이 바뀌면 다시 확인해요.</Text>
            </Panel>)}
            <Button label={busy?'최신 조건을 확인하고 있어요':'확인한 조건으로 예상 계산'} disabled={busy} onPress={()=>void run(async()=>{if(mode==='PUBLIC'&&(!runtimeTime().trusted||!safetyValid(cache.safety,runtimeTime().now)||runtimeTime().now-cache.safety!.receivedAt>60000))try{await refresh();}catch{}setWallNow(runtimeTime().now);setShowResult(true);})}/>
            {showResult&&calculation?.error&&<Panel title="예상 계산을 보류했어요." tone="warning">{description(calculation.error)}</Panel>}
            {showResult&&calculation?.result&&<Panel title="확인한 조건 기준 예상">
              {description('개인 자격과 매장의 실제 적용은 별도 확인이 필요해요.')}
              {calculation.result.best? <>
                <Text style={s.subtitle}>먼저 해야 할 사용 순서</Text>{calculation.result.best.ruleIds.flatMap(rid=>catalog.rules.find(r=>r.id===rid)?.usageSteps??[]).map((step,i)=><Text key={i} style={s.body}>{i+1}. {step}</Text>)}
                {[['즉시 할인 예상',calculation.result.best.instantWon],['지금 결제액 예상',calculation.result.best.payableWon],['청구 할인 예상',calculation.result.best.billingWon]].map(([label,value])=><View key={label} accessible accessibilityLabel={`${label}, ${money(value as number)}`} style={s.amountRow}><Text style={s.body}>{label}</Text><Text style={s.amount}>{money(value as number)}</Text></View>)}
              </>:description('조건 모름·미충족 또는 자료 제한으로 예상 숫자를 표시하지 않아요.')}
              {mode==='PUBLIC'&&selected.some(pid=>data.wallet.find(w=>w.id===pid)?.productVersion===null)&&<Text style={s.warning}>상품 버전 모름인 수단을 계산에서 제외했어요. 지갑에서 확인해 주세요.</Text>}
              {calculation.result.results.filter(result=>visibleRules.some(r=>r.id===result.ruleId)).map(result=>{const r=catalog.rules.find(r=>r.id===result.ruleId)!;const source=catalog.sources.find(x=>x.id===r.sourceId);return <View key={r.id} style={s.ruleResult}><Text style={s.subtitle}>{r.title}</Text><Text style={s.body}>{result.eligibility==='UNKNOWN'?'조건 확인 필요':result.eligibility==='FALSE'?'이 조건에서는 계산 대상이 아니에요.':'입력한 조건을 충족한 예상 후보예요.'}</Text>{result.reasons.map(reason=><Text key={reason} style={s.body}>• {reasonText(reason)}</Text>)}
                {!r.calculation&&<Text style={s.body}>안내 전용: {r.unsupportedReason??'지원하지 않는 산식이에요.'}</Text>}
                <Text style={s.small}>출처: {r.origin==='USER_INPUT'?'내가 직접 작성 · 실제 원문 검수 없음':source?.documentVersion??'출처 확인 필요'}{'\n'}{r.origin==='USER_INPUT'?'작성·수정일':'원문 확인일'}: {r.origin==='USER_INPUT'?data.ruleWrittenAt[r.id]??'기록 없음':source?.checkedAt??'모름'}{'\n'}적용 기간: {r.startsAt} ~ {r.endsAt} (종료 시각 미포함)</Text>
                {source&&r.origin==='CATALOG'&&<Text style={s.small}>원문 기한: {source.freshUntil} · 이용권 기한: {source.rightsUntil}</Text>}
                {r.usageSteps.map((step,i)=><Text key={i} style={s.body}>사용 {i+1}. {step}</Text>)}{r.exclusions.map((ex,i)=><Text key={i} style={s.small}>제외: {ex}</Text>)}
                {source&&r.origin==='CATALOG'&&source.rights.display&&<Button label="공식 원문 확인" secondary onPress={()=>void run(async()=>{await Linking.openURL(source.url);})}/>}
                {r.origin==='USER_INPUT'&&<>{data.ruleSourceUrl[r.id]&&<><Text style={s.small}>사용자가 입력한 확인 링크: {data.ruleSourceUrl[r.id]}</Text><Button label="내가 입력한 확인 링크 열기 (미검수)" secondary onPress={()=>void run(async()=>{await Linking.openURL(data.ruleSourceUrl[r.id]);})}/></>}<Button label="직접 작성 조건 수정" secondary onPress={()=>openPersonalRule(r)}/><Button label="직접 작성 조건 삭제" danger onPress={()=>void run(async()=>{const next={...data,rules:data.rules.filter(x=>x.id!==r.id),ruleWrittenAt:{...data.ruleWrittenAt},ruleSourceUrl:{...data.ruleSourceUrl},conditions:{...data.conditions}};delete next.conditions[r.id];delete next.ruleWrittenAt[r.id];delete next.ruleSourceUrl[r.id];await persist(next);})}/></>}
                {r.origin==='CATALOG'&&<Button label="이 혜택 오류 제보" secondary onPress={()=>{setReportRule(r.id);setReportOpen(true);}}/>}
              </View>;})}
              {!visibleRules.length&&description('선택한 조건의 지원 자료가 없어요. 브랜드·점포·결제 채널·보유 수단을 다시 확인해 주세요.')}
            </Panel>}
          </>}
          <Panel title="근처 목록을 직접 요청해요.">{description('위치는 단말에서 거리 순서를 계산하는 데만 사용해요. 점포 위치가 할인 적용을 증명하지 않아요.')}
            {!data.consent.location?<Button label="전경 위치 목적을 읽고 동의" secondary onPress={()=>void run(()=>consent('location',true))}/>:<Button label="현재 위치로 근처 지원 점포 찾기" secondary disabled={busy} onPress={()=>void run(async()=>{if(mode!=='PUBLIC'||!runtimeTime().trusted||!safetyValid(cache.safety,runtimeTime().now)||!cache.safety?.flags.foregroundLocation)throw Error('현재 전경 위치 기능은 준비 중이에요. 지역과 점포를 직접 선택해 주세요.');const location=await foregroundPosition();if(location.coords.accuracy===null||location.coords.accuracy>50)throw Error('정확한 근처 순서를 확인하기 어려워요. 지역을 직접 선택해 주세요.');setNearby(catalog.places.filter(p=>!region||p.regionId===region).map(p=>({id:p.id,name:p.name,distance:distanceMeters(location.coords,p)})).sort((a,b)=>a.distance-b.distance));})}/>}
            {nearby.map(p=><Button key={p.id} label={`${p.name} · 약 ${Math.round(p.distance)}m`} secondary onPress={()=>{const choice=catalog.places.find(x=>x.id===p.id)!;setBrand(choice.brandId);setPlace(choice.id);}}/>)}
          </Panel>
        </>}
      </>}
      {tab==='내 지갑'&&<><Text accessibilityRole="header" style={s.title}>내 지갑</Text><Text style={s.body}>카드 번호 없이 상품과 등급만.{ '\n' }내 정보는 이 단말에 보관해요.</Text>
        {!data.wallet.length&&<Panel title="가진 수단 하나부터 등록해요.">{description('모르는 상품 버전과 멤버십 등급은 모름으로 저장할 수 있어요.')}</Panel>}
        {data.wallet.map(w=><Panel key={w.id} title={w.name}><Text style={s.body}>{w.kind==='CARD'?'결제 카드':'멤버십'} · {w.tier}</Text><Text style={s.small}>상품 버전: {w.productVersion??'모름'}</Text><Button label={`${w.name} 수정`} secondary onPress={()=>{setWallet({...w});setEditingWallet(true);}}/><Button label={`${w.name} 삭제`} danger onPress={()=>void run(async()=>{pauseNative();await persist(updateWallet(data,null,w.id,cache.catalog?.rules??[]));await stopNative();setSelected(prev=>prev.filter(pid=>pid!==w.id));setMessage('보유 수단과 연결된 직접 작성 조건을 삭제했어요.');})}/></Panel>)}
        <Button label="보유 수단 등록" disabled={!loaded||busy} onPress={()=>{setWallet(newWallet());setEditingWallet(false);}}/>
        <Button label="내 조건 직접 작성" secondary disabled={!loaded||busy} onPress={()=>{setTab('혜택');void changeMode('PERSONAL');openPersonalRule();}}/>
      </>}
      {wallet&&<Panel title={editingWallet?'보유 수단 수정':'보유 수단 등록'}>
        {!editingWallet&&!!cache.catalog?.products.length&&<Choices label="공개 지원 상품 (해당하면 선택)" options={cache.catalog.products} value={wallet.id} onChange={pid=>{const product=cache.catalog!.products.find(p=>p.id===pid)!;setWallet({...wallet,id:pid,name:product.name,kind:product.kind});}}/>}
        <Choices label="보유 수단 종류" value={wallet.kind} options={[{id:'CARD',name:'카드'},{id:'MEMBERSHIP',name:'멤버십'}]} onChange={kind=>setWallet({...wallet,kind:kind as WalletItem['kind']})}/>
        <Field label="상품·멤버십 이름" value={wallet.name} onChange={name=>setWallet({...wallet,name})}/>
        <Field label="현재 등급·혜택 유형 (모르면 모름)" value={wallet.tier} onChange={tier=>setWallet({...wallet,tier})}/>
        <Field label="상품·발급 버전 (비우면 모름)" value={wallet.productVersion??''} onChange={version=>setWallet({...wallet,productVersion:version.trim()||null})}/>
        <Text style={s.small}>카드번호·CVC·금융 로그인 정보를 입력하지 마세요.</Text>
        <Button label="보유 수단 저장" disabled={busy} onPress={()=>void run(async()=>{if(!wallet.name.trim())throw Error('상품 이름을 입력해 주세요.');if(!editingWallet&&data.wallet.some(w=>w.id===wallet.id))throw Error('이미 등록한 상품이에요. 기존 항목을 수정해 주세요.');const item={...wallet,name:wallet.name.trim(),tier:wallet.tier.trim()||'모름'};pauseNative();await persist(updateWallet(data,item,item.id,cache.catalog?.rules??[]));await stopNative();setWallet(null);setMessage('보유 수단을 단말에 저장했어요.');})}/><Button label="등록 취소" secondary onPress={()=>setWallet(null)}/>
      </Panel>}
      {rule&&<Panel title="내 조건 직접 작성 · 미검수">
        <Field label="확인할 웹 링크 (선택, HTTPS)" value={ruleSource} onChange={setRuleSource} maxLength={2000}/><Field label="조건 제목" value={rule.title} onChange={title=>setRule({...rule,title})}/><Field label="적용 브랜드 이름" value={rule.brandId} onChange={brandId=>setRule({...rule,brandId})}/>
        <Choices label="보유 수단" options={data.wallet.map(w=>({id:w.id,name:w.name}))} value={rule.productId} onChange={productId=>setRule({...rule,productId,requiredConditions:[data.wallet.find(w=>w.id===productId)?.kind==='CARD'?'spend':'tier','productVersion','eligibleItems']})}/>
        <Choices label="사용 채널" options={[{id:'OFFLINE',name:'매장'},{id:'ONLINE',name:'온라인'},{id:'APP',name:'공식 앱'}]} value={rule.channels[0]} onChange={value=>setRule({...rule,channels:[value]})}/>
        <Choices label="산식" options={[{id:'PERCENT',name:'정률 (100 = 1%)'},{id:'FIXED',name:'정액 (원)'}]} value={rule.calculation?.kind??'PERCENT'} onChange={value=>setRule({...rule,calculation:{...rule.calculation!,kind:value as 'PERCENT'|'FIXED'}})}/>
        <Field label={rule.calculation?.kind==='PERCENT'?'비율 (basis points, 100 = 1%)':'할인액 (원)'} numeric value={ruleValue} onChange={setRuleValue}/><Field label="건당 할인 상한 (원)" value={ruleCap} numeric onChange={setRuleCap}/><Field label="최소 원 결제금액 (원)" value={ruleMinimum} numeric onChange={setRuleMinimum}/>
        <Choices label="할인 기준금액" value={rule.calculation?.basis??'ORIGINAL'} options={[{id:'ORIGINAL',name:'원 결제금액'},{id:'ELIGIBLE',name:'대상 품목 금액'}]} onChange={value=>setRule({...rule,calculation:{...rule.calculation!,basis:value as 'ORIGINAL'|'ELIGIBLE'}})}/>
        <Choices label="원 미만 처리" value={rule.calculation?.rounding??'FLOOR'} options={[{id:'FLOOR',name:'버림'},{id:'HALF_UP',name:'반올림'},{id:'CEIL',name:'올림'}]} onChange={value=>setRule({...rule,calculation:{...rule.calculation!,rounding:value as 'FLOOR'|'HALF_UP'|'CEIL'}})}/>
        <Choices label="할인 정산 시점" value={rule.calculation?.settlement??'INSTANT'} options={[{id:'INSTANT',name:'즉시 할인'},{id:'BILLING',name:'청구 할인'}]} onChange={value=>setRule({...rule,calculation:{...rule.calculation!,settlement:value as 'INSTANT'|'BILLING'}})}/>
        <Field label="시작 시각 (UTC RFC3339)" value={rule.startsAt} onChange={startsAt=>setRule({...rule,startsAt})}/><Field label="종료 시각 (UTC RFC3339, 해당 시각 미포함)" value={rule.endsAt} onChange={endsAt=>setRule({...rule,endsAt})}/>
        <Field label="결제 전 사용 순서 (한 줄에 한 단계)" value={rule.usageSteps.join('\n')} multiline maxLength={800} onChange={value=>setRule({...rule,usageSteps:value.split('\n').filter(Boolean)})}/><Field label="제외 조건 (한 줄에 한 조건)" value={rule.exclusions.join('\n')} multiline maxLength={800} onChange={value=>setRule({...rule,exclusions:value.split('\n').filter(Boolean)})}/>
        <Text style={s.warning}>직접 작성은 실제 원문 검수가 아니에요. 잔여 한도·횟수·자격은 계산할 때 다시 확인해요. 직접 작성 규칙의 중복 합산은 제공하지 않아요.</Text>
        <Button label="직접 작성 조건 저장" disabled={busy} onPress={()=>void run(async()=>{if(!rule.title.trim()||!rule.brandId.trim())throw Error('제목과 브랜드를 입력해 주세요.');const value=parseWon(ruleValue),cap=parseWon(ruleCap),minimum=parseWon(ruleMinimum);if(value===null||cap===null||minimum===null)throw Error('산식과 상한·최소금액을 확인해 주세요.');if(rule.calculation!.kind==='PERCENT'&&value>10000)throw Error('비율은 0~10,000 basis points예요.');if(ruleSource){const url=new URL(ruleSource);if(url.protocol!=='https:'||url.username||url.password)throw Error('HTTPS 확인 링크를 입력해 주세요.');}const saved={...rule,version:id(),calculation:{...rule.calculation!,value,capWon:cap,minimumWon:minimum}};const next={...data,rules:[...data.rules.filter(r=>r.id!==saved.id),saved],ruleWrittenAt:{...data.ruleWrittenAt,[saved.id]:new Date().toISOString()},ruleSourceUrl:{...data.ruleSourceUrl,[saved.id]:ruleSource},conditions:{...data.conditions}};delete next.conditions[saved.id];await persist(next);setRule(null);setMode('PERSONAL');setBrand(saved.brandId);setSelected([saved.productId]);setShowResult(false);setMessage('내 조건을 단말에 저장했어요.');})}/><Button label="작성 취소" secondary onPress={()=>setRule(null)}/>
      </Panel>}
      {tab==='설정'&&<><Text accessibilityRole="header" style={s.title}>설정</Text><Panel title="내 정보의 처리">{description('지갑·개인 조건·현재 위치는 단말에서 처리해요. 계정·금융 실적 자동 조회·서버 위치 이력·푸시 토큰은 사용하지 않아요. 선택한 오류 제보만 서버로 보내요.')}<Text style={s.small}>연결 주소: {(()=>{try{return apiBase();}catch{return '운영 HTTPS 연결 주소 필요';}})()}{'\n'}휴대폰의 127.0.0.1은 휴대폰 자신이에요. 개발 빌드에 Mac LAN 주소를 설정해 주세요.</Text></Panel>
        <Panel title="전경 위치 선택 동의">{description('직접 요청한 근처 목록의 거리 계산에만 위치를 사용해요. 동의와 OS 권한은 각각 선택해요.')}<Choices label="전경 위치 목적 동의" value={String(data.consent.location)} options={[{id:'false',name:'동의 안 함'},{id:'true',name:'동의'}]} onChange={v=>void run(()=>consent('location',v==='true'))}/></Panel>
        <Panel title="주변 자동 알림은 준비 중이에요.">{description('OS·장소별 검증, 자료 이용권, 법률 확인 전 공개 기능은 OFF예요. 개발 파일럿은 실제 관측이 부족하면 알리지 않아요.')}<Text style={s.small}>iOS flag: {cache.safety?.flags.iosBackground?'ON':'OFF'} · Android flag: {cache.safety?.flags.androidBackground?'ON':'OFF'}</Text>
          {__DEV__&&<><Choices label="개발 파일럿 선택 동의" value={String(data.consent.background)} options={[{id:'false',name:'동의 안 함'},{id:'true',name:'동의'}]} onChange={v=>void run(()=>consent('background',v==='true'))}/><Choices label="광고성 정보 수신 선택 동의" value={String(data.consent.advertising)} options={[{id:'false',name:'동의 안 함'},{id:'true',name:'동의'}]} onChange={v=>void run(()=>consent('advertising',v==='true'))}/><Text style={s.small}>일 최대 2건, 브랜드·장소 24시간 간격. 21:00~08:00에는 보내지 않고 다음 아침으로 넘기지 않아요.</Text><Button label="허용 범위의 네이티브 파일럿 시작" secondary disabled={busy} onPress={()=>void run(async()=>{await startPilot();setMessage('지역 후보 등록을 시작했어요. 관측·조건 통과를 보장하지 않아요.');})}/></>}
          <Button label="동의 철회 · 자동 작업과 알림 정리" secondary disabled={busy} onPress={()=>void run(async()=>{pauseNative();await persist({...data,consent:{...data.consent,background:false,advertising:false,location:false,updatedAt:new Date().toISOString()}});await stopNative();setMessage('동의를 철회하고 자동 작업·알림을 정리했어요.');})}/><Button label="OS 권한 설정 열기" secondary onPress={()=>void Linking.openSettings()}/><Text style={s.small}>동의 버전: {data.consent.version} · 변경일: {data.consent.updatedAt}</Text>
        </Panel>
        <Panel title="오류 제보">{description('카드번호·이름·연락처·좌표·거래내역을 입력하지 마세요. 제보 본문은 운영자가 조회할 수 있어요.')}<Button label="오류 제보 작성" secondary onPress={()=>{setReportOpen(true);setReportRule('');}}/>{!data.reports.length&&<Text style={s.small}>이 단말에 보관한 제보 삭제 토큰이 없어요.</Text>}{data.reports.map(r=><View key={r.id} style={s.ruleResult}><Text selectable style={s.small}>제보 ID: {r.id}{'\n'}삭제 토큰: {r.deleteToken}</Text><Button label={`제보 ${r.id} 서버에서 삭제`} danger disabled={busy} onPress={()=>void run(async()=>{await request('/v1/reports/'+encodeURIComponent(r.id),{method:'DELETE',headers:{Authorization:'Bearer '+r.deleteToken}});await persist({...data,reports:data.reports.filter(x=>x.id!==r.id)});setMessage('서버 제보를 삭제했어요.');})}/></View>)}</Panel>
        <Panel title="단말 데이터 전체 삭제">{description('지갑·직접 작성·조건·캐시·동의·보호 키·위치 작업·예약 및 표시 알림을 정리해요. 서버에 제출한 제보는 위 삭제 토큰으로 별도 삭제해 주세요. 앱 삭제만으로 iOS Keychain 잔존이 사라진다고 보장하지 않아요.')}
          {deleteConfirm?<><Text style={s.warning}>삭제 토큰도 사라져요. 필요한 서버 제보를 먼저 삭제하거나 토큰을 보관해 주세요.</Text><Button label="확인 · 이 단말 데이터 모두 삭제" danger disabled={busy} onPress={()=>void run(async()=>{const remoteDeleted=await clearDeviceBeforeRemoteReport(pendingReceipt,pauseNative,async()=>{await deleteDeviceData();setData(emptyLocal());setCache({catalog:null,safety:null});setSelected([]);setBrand('');setPlace('');setMode('PUBLIC');setDemo(null);setDemoConditions({});setAmount('');setEligible('');setWallet(null);setRule(null);setReportOpen(false);setReportMessage('');setNearby([]);setShowResult(false);setDeleteConfirm(false);setLoaded(true);setTab('혜택');setMessage('단말 데이터를 삭제했어요. 지갑·캐시·설정·위치 작업·알림을 정리했어요.');AccessibilityInfo.announceForAccessibility('단말 데이터를 삭제했어요.');},async receipt=>{await request('/v1/reports/'+encodeURIComponent(receipt.id),{method:'DELETE',headers:{Authorization:'Bearer '+receipt.deleteToken}});},setPendingReceipt);if(!remoteDeleted){const warning='단말 데이터는 삭제했어요. 서버 제보 삭제는 연결 문제로 완료하지 못했어요. 화면의 삭제 토큰을 보관하고 다시 시도해 주세요.';setError(warning);AccessibilityInfo.announceForAccessibility(warning);}})}/><Button label="전체 삭제 취소" secondary onPress={()=>setDeleteConfirm(false)}/></>:<Button label="단말 데이터 전체 삭제" danger onPress={()=>setDeleteConfirm(true)}/>}
        </Panel>
      </>}
      {reportOpen&&<Panel title="오류 제보 작성"><Text style={s.small}>민감정보 없이 조건 오류를 설명해 주세요. 지갑·현재 위치는 자동으로 첨부하지 않아요.</Text><Choices label="제보 종류" value={reportCategory} options={[{id:'CONDITION',name:'조건 오류'},{id:'EXPIRED',name:'기간·차단'},{id:'PLACE',name:'점포 오류'},{id:'OTHER',name:'기타'}]} onChange={setReportCategory}/><Field label="문제 규칙 ID (선택)" value={reportRule} onChange={setReportRule} maxLength={200}/><Field label="비개인 설명 (최대 2,000자)" value={reportMessage} onChange={setReportMessage} multiline maxLength={2000}/><Button label="제보 전송" disabled={busy} onPress={()=>void run(async()=>{if(!reportMessage.trim())throw Error('비개인 설명을 입력해 주세요.');if(pendingReceipt)throw Error('저장하지 못한 제보의 삭제 토큰을 먼저 보관하거나 서버에서 삭제해 주세요.');await submitReportSafely(data,async()=>await (await request('/v1/reports',{method:'POST',body:JSON.stringify({...(reportRule?{ruleId:reportRule}:{}),category:reportCategory,message:reportMessage})})).json(),persist,async receipt=>{await request('/v1/reports/'+encodeURIComponent(receipt.id),{method:'DELETE',headers:{Authorization:'Bearer '+receipt.deleteToken}});},setPendingReceipt);setReportOpen(false);setReportMessage('');setMessage('제보를 보냈어요. 설정에서 삭제 토큰을 보관하고 제보를 삭제할 수 있어요.');setTab('설정');})}/><Button label="제보 작성 취소" secondary onPress={()=>setReportOpen(false)}/></Panel>}
      {!!message&&tab!=='혜택'&&<Text accessibilityLiveRegion="polite" style={s.small}>{message}</Text>}
      <Text style={s.footnote}>혜택패스 검증판 · 실제 적용 보장 없음</Text>
    </ScrollView>{footer}</KeyboardAvoidingView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:color.background,paddingTop:Platform.OS==='android'?StatusBar.currentHeight??24:0},header:{paddingHorizontal:20,paddingVertical:14,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:'#D7DED4'},brand:{fontSize:23,fontWeight:'800',color:color.brand},badge:{backgroundColor:color.accent,padding:8,borderRadius:8,color:color.text,fontSize:14,fontWeight:'700'},content:{padding:20,gap:16,maxWidth:700,width:'100%',alignSelf:'center',paddingBottom:32},title:{fontSize:30,lineHeight:40,fontWeight:'800',color:color.text},subtitle:{fontSize:22,lineHeight:31,fontWeight:'700',color:color.text,marginBottom:8},body:{fontSize:17,lineHeight:26,color:color.text,flexShrink:1},small:{fontSize:14,lineHeight:22,color:color.muted},label:{fontSize:17,lineHeight:26,fontWeight:'600',color:color.text},card:{padding:20,gap:12,borderRadius:16,backgroundColor:'white',borderWidth:1,borderColor:'#D7DED4'},banner:{padding:16,borderRadius:12,backgroundColor:color.accent},button:{minHeight:48,justifyContent:'center',alignItems:'center',paddingHorizontal:16,paddingVertical:12,backgroundColor:color.brand,borderRadius:10,borderWidth:1,borderColor:color.brand},secondary:{backgroundColor:'white',borderColor:color.border},danger:{backgroundColor:'#B3261E',borderColor:'#B3261E'},buttonText:{fontSize:17,lineHeight:26,fontWeight:'700',color:'white',textAlign:'center'},field:{gap:8},input:{minHeight:50,fontSize:17,lineHeight:26,padding:12,borderColor:color.border,borderWidth:1,borderRadius:10,color:color.text,backgroundColor:'white'},choices:{gap:8},choice:{minHeight:48,padding:12,borderWidth:1,borderColor:color.border,borderRadius:10,backgroundColor:'white',gap:4},selected:{backgroundColor:color.brand,borderColor:color.brand},warning:{fontSize:17,lineHeight:26,color:'#785100'},amountRow:{paddingVertical:12,gap:4,borderBottomWidth:1,borderBottomColor:'#D7DED4'},amount:{fontSize:28,lineHeight:38,fontWeight:'800',color:color.brand},ruleResult:{gap:10,paddingTop:20,borderTopWidth:1,borderTopColor:'#D7DED4'},nav:{flexDirection:'row',borderTopWidth:1,borderTopColor:'#D7DED4',backgroundColor:'white'},navItem:{flex:1,minHeight:58,alignItems:'center',justifyContent:'center',paddingVertical:12,paddingHorizontal:4},footnote:{fontSize:14,lineHeight:22,color:color.muted,textAlign:'center',paddingTop:16}});
