import test from 'node:test';
import assert from 'node:assert/strict';
import {parseWon, splitProtectedText, normalizeLocal, personalCatalog, unknownConditions} from '../src/model.ts';
import {calculate} from '../../../packages/benefit-core/src/index.ts';
test('KRW input is integer and unknown remains null',()=>{assert.equal(parseWon(''),null);assert.equal(parseWon('모름'),null);assert.equal(parseWon('12,000'),12000);assert.throws(()=>parseWon('1.5'));assert.throws(()=>parseWon('-1'));assert.throws(()=>parseWon('1000000001'));});
test('Korean protected storage chunks preserve bytes and text',()=>{const text='지갑🔒'.repeat(1000);const chunks=splitProtectedText(text);assert.equal(chunks.join(''),text);assert(chunks.every(s=>new TextEncoder().encode(s).length<=1600));});
test('local unreviewed rule stays personal and unknown never becomes a sum',()=>{const now=Date.now();const data=normalizeLocal({wallet:[{id:'w',name:'내 카드',kind:'CARD',tier:'모름',productVersion:null}],rules:[{id:'p',version:'1',origin:'USER_INPUT',title:'내 조건',productId:'w',brandId:'내 매장',sourceId:'personal',channels:['OFFLINE'],placeIds:[],startsAt:new Date(now-1000).toISOString(),endsAt:new Date(now+86400000).toISOString(),status:'DRAFT',requiredConditions:['spend'],remainingWonRequired:true,remainingUsesRequired:true,calculation:{kind:'FIXED',value:1000,basis:'ORIGINAL',minimumWon:0,minimumBasis:'ORIGINAL',capWon:1000,rounding:'FLOOR',settlement:'INSTANT'},usageSteps:['결제 전 확인'],exclusions:[]}]});const catalog=personalCatalog(data,now);const result=calculate({amountWon:12000,brandId:'내 매장',placeId:'',channel:'OFFLINE',productIds:['w'],catalog,conditions:unknownConditions(catalog.rules,now),now,mode:'PERSONAL'});assert.equal(result.best,null);assert.equal(result.results[0].eligibility,'UNKNOWN');assert.equal(catalog.rules[0].origin,'USER_INPUT');});
import {writeProtected, readProtected, removeProtected} from '../src/protected.ts';
test('a failed protected save keeps the previous committed wallet',async()=>{const entries=new Map<string,string>();let fail=false;const store={get:async(k:string)=>entries.get(k)??null,set:async(k:string,v:string)=>{if(fail&&k.endsWith('.1'))throw Error('full');entries.set(k,v);},remove:async(k:string)=>{entries.delete(k);}};await writeProtected(store,'wallet',{name:'old'});fail=true;await assert.rejects(writeProtected(store,'wallet',{name:'지갑'.repeat(1000)}));assert.deepEqual(await readProtected(store,'wallet'),{name:'old'});await removeProtected(store,'wallet');assert.equal(entries.size,0);});
