import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyLocal, personalCatalog, updateWallet, submitReportSafely, clearDeviceBeforeRemoteReport} from '../src/model.ts';
import {clockAnchor, sampleClock, runSerial, type SerialState, initializeInstallation} from '../src/runtime-safety.ts';
import {calculate,safetyValid} from '../../../packages/benefit-core/src/index.ts';
import {input} from '../../../packages/benefit-core/test/fixtures.ts';
test('wallet qualifications invalidate public and personal conditions on edit and deletion',()=>{const x=input();const data=emptyLocal();data.wallet=[{id:'card',name:'카드',kind:'CARD',tier:'VIP',productVersion:'2026'}];data.rules=[{...x.catalog.rules[1],id:'personal-card',origin:'USER_INPUT',sourceId:'personal'}];data.conditions={...x.conditions,'personal-card':x.conditions.c};assert(calculate({...x,mode:'PERSONAL',catalog:personalCatalog(data,x.now),conditions:data.conditions,productIds:['card']}).best);
for(const patch of [{tier:'모름'},{productVersion:null},{kind:'MEMBERSHIP' as const}]){const changed=updateWallet(data,{...data.wallet[0],...patch},'card',x.catalog.rules);assert.equal(changed.conditions.c,undefined);assert.equal(changed.conditions['personal-card'],undefined);}
const edited=updateWallet(data,{...data.wallet[0],tier:'모름',productVersion:null},'card',x.catalog.rules);assert.equal(calculate({...x,mode:'PERSONAL',catalog:personalCatalog(edited,x.now),conditions:edited.conditions,productIds:['card']}).best,null);assert.equal(edited.conditions.c,undefined);assert.equal(edited.conditions['personal-card'],undefined);assert.deepEqual(edited.conditions.m,x.conditions.m);const renamed=updateWallet(data,{...data.wallet[0],name:'다른 표시명'},'card',x.catalog.rules);assert.deepEqual(renamed.conditions.c,x.conditions.c);const deleted=updateWallet(data,null,'card',x.catalog.rules);assert.equal(deleted.conditions.c,undefined);assert.equal(deleted.rules.length,0);});
test('51st report is rejected before POST; failed persistence rolls back or preserves a visible receipt',async()=>{const data=emptyLocal();data.reports=Array.from({length:50},(_,i)=>({id:String(i),deleteToken:'token'}));let posts=0;const post=async()=>{posts++;return {id:'new',deleteToken:'secret'};};await assert.rejects(submitReportSafely(data,post,async()=>{},async()=>{},()=>{}));assert.equal(posts,0);data.reports=[];let pending:unknown=null,deleted=0;await assert.rejects(submitReportSafely(data,post,async()=>{throw Error('full');},async()=>{deleted++;},receipt=>{pending=receipt;}));assert.equal(deleted,1);assert.equal(pending,null);await assert.rejects(submitReportSafely(data,post,async()=>{throw Error('full');},async()=>{throw Error('offline');},receipt=>{pending=receipt;}));assert.deepEqual(pending,{id:'new',deleteToken:'secret'});});
test('clock drift or rollback stays uncertain until a fresh anchor; normal elapsed time and exact expiry are distinct',()=>{const c=clockAnchor(1_000_000,100);assert(sampleClock(c,1_060_000,60_100));assert.equal(sampleClock(c,1_059_999,60_101),false);assert.equal(sampleClock(c,1_060_002,60_102),false);const fresh=clockAnchor(1_060_002,60_102);assert(sampleClock(fresh,1_061_002,61_102));assert.equal(sampleClock(fresh,1_066_002,62_102),false);const d=clockAnchor(1_000_000,100);assert(sampleClock(d,1_000_000+86_400_000,100+86_400_000));assert.equal(safetyValid({...input().safety!,receivedAt:d.wall,serverTime:new Date(d.wall).toISOString()},d.wall+86_400_000),false);});
test('a backup without a cache marker clears protected state before recreating the marker',async()=>{const calls:string[]=[];await initializeInstallation(false,async()=>{calls.push('stop');},async()=>{calls.push('clear');},()=>{calls.push('marker');});assert.deepEqual(calls,['stop','clear','marker']);calls.length=0;await initializeInstallation(true,async()=>{calls.push('stop');},async()=>{calls.push('clear');},()=>{calls.push('marker');});assert.deepEqual(calls,['stop']);});
test('revocation during an actual async barrier cancels queued delivery; serialized counters cap two deliveries',async()=>{const state:SerialState={generation:0,tail:Promise.resolve()};let release!:()=>void,reached!:()=>void;const barrier=new Promise<void>(r=>release=r),started=new Promise<void>(r=>reached=r);let delivered=0;const inFlight=runSerial(state,async valid=>{reached();await barrier;if(valid())delivered++;});await started;const queued=runSerial(state,async valid=>{if(valid())delivered++;});state.generation++;release();await Promise.all([inFlight,queued]);assert.equal(delivered,0);let count=0;await Promise.all(Array.from({length:5},()=>runSerial(state,async valid=>{const previous=count;await Promise.resolve();if(valid()&&previous<2){count=previous+1;delivered++;}})));assert.equal(count,2);assert.equal(delivered,2);});
test('offline remote deletion cannot delay local clearing or lose the pending receipt',async()=>{
  const receipt={id:'unsaved',deleteToken:'secret'};let pending:typeof receipt|null=receipt;const calls:string[]=[];let wallet=['card'],consent=true,cache=['catalog'];
  let release!:()=>void,reached!:()=>void;const offlineBarrier=new Promise<void>(r=>release=r),remoteStarted=new Promise<void>(r=>reached=r);
  const deleting=clearDeviceBeforeRemoteReport(receipt,()=>{calls.push('pause');},async()=>{calls.push('stop');wallet=[];consent=false;cache=[];calls.push('clear');},async saved=>{assert.deepEqual(saved,receipt);calls.push('remote');reached();await offlineBarrier;throw Error('offline');},saved=>{pending=saved;});
  assert.deepEqual(calls,['pause','stop','clear']);await remoteStarted;assert.deepEqual(wallet,[]);assert.equal(consent,false);assert.deepEqual(cache,[]);assert.deepEqual(pending,receipt);release();assert.equal(await deleting,false);assert.deepEqual(pending,receipt);assert.deepEqual(calls,['pause','stop','clear','remote']);
  assert.equal(await clearDeviceBeforeRemoteReport(receipt,()=>{},async()=>{},async()=>{},saved=>{pending=saved;}),true);assert.equal(pending,null);
});
