import './style.css';
import {validateCatalog,kstMonth} from '../../../packages/benefit-core/src/index.ts';
import type {Bootstrap,Catalog,RuleConditions,Truth,Review} from '../../../contracts/types.ts';
import {previewDraft} from './preview.ts';
import {ensureLocalRole,operationError,reportUpdateInput,reviewInput} from './operations.ts';
import empty from '../../../contracts/empty-catalog.json';
import {conditionLabel,reasonText} from '../../mobile/src/model.ts';
const logo=new URL('../../../assets/brand/sseulttae/logo.svg',import.meta.url).href;
interface Entry {id:string;releaseId:string;status:string;author:string;createdAt:string;catalog:Catalog;review:Review|null}
interface Report {id:string;ruleId?:string;category:string;message:string;status:string;createdAt:string}
interface Audit {id:number;actor:string;action:string;target:string;createdAt:string}
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<a class="skip-link" href="#workspace">본문으로 이동</a>
<header><img src="${logo}" alt="쓸때"><div><p class="eyebrow">운영 작업 공간</p><h1>자료와 안전을 함께 관리해요</h1></div><span id="connection-state" class="badge">연결 확인 전</span></header>
<div class="workspace"><aside><nav aria-label="관리 업무">
<button data-go="dashboard" aria-current="page">대시보드<span>현재 상태와 다음 작업</span></button>
<button data-go="catalogs">자료·검수<span>초안부터 게시까지</span></button>
<button data-go="reports">제보함<span>분류·종결·삭제</span></button>
<button data-go="safety">안전 중단<span>차단·롤백·복구</span></button>
<button data-go="audit">감사 기록<span>수행자와 변경 내역</span></button>
</nav><p class="aside-note">공개 계산에는 이용권 7개 항목과 작성자 외 실제 사람의 원문 검수가 필요합니다.</p></aside>
<main id="workspace" tabindex="-1">
<details class="connection"><summary>연결 설정과 관리자 인증</summary><div class="grid"><label>API 주소<input id="base" value="http://127.0.0.1:8080" type="url"></label><label>개발 권한 시험<select id="subject"><option value="author">작성자 author</option><option value="reviewer">검수자 reviewer</option><option value="publisher">게시자 publisher</option></select></label><label>운영 Bearer JWT (선택, 이 페이지 메모리에만 보관)<input id="jwt" type="password" autocomplete="off"></label></div><p>로컬 역할은 loopback 서버의 권한 시험 identity입니다. 실제 사람 인증·원문 검수 증거가 아닙니다. 운영 JWT의 역할·MFA·subject 허용 목록은 서버가 판정합니다.</p><button id="reload" class="secondary">현재 자료 새로고침</button></details>
<div id="status" role="status" aria-live="polite">연결 설정을 확인하고 현재 자료를 새로고침해 주세요.</div>
<section data-view="dashboard" aria-labelledby="dashboard-title"><div class="section-heading"><div><p class="eyebrow">오늘의 운영</p><h2 id="dashboard-title" tabindex="-1">대시보드</h2></div><button id="dashboard-reload" class="secondary">상태 새로고침</button></div>
<p id="active">현재 게시 버전: 확인 필요</p><p id="checked-at" class="muted">아직 서버 상태를 조회하지 않았습니다.</p>
<div class="metrics"><article><span>조회한 작성 중 자료</span><strong id="draft-count">—</strong><button data-go="catalogs" class="text-button">자료 보기 →</button></article><article><span>검수 등록 · 게시 대기</span><strong id="review-count">—</strong><p>실제 원문 증거는 별도 대조</p></article><article><span>조회한 미종결 제보</span><strong id="report-count">조회 전</strong><button data-go="reports" class="text-button">제보함 열기 →</button></article><article><span>공개 계산 기능</span><strong id="catalog-state">확인 전</strong><button data-go="safety" class="text-button">안전 상태 보기 →</button></article></div>
<div class="grid"><article><h3>자료를 게시하는 순서</h3><ol><li>이용권과 원문 증거를 비공개 저장소에서 대조</li><li>작성자가 초안을 입력·형식 검사</li><li>다른 실제 사람이 원문·골든 사례 검수</li><li>게시자가 현재 버전을 확인하고 게시</li></ol><button data-go="catalogs">자료·검수 열기</button></article><article><h3>안전 상태</h3><div id="safety-summary">아직 조회하지 않았습니다.</div><p>차단과 OFF는 롤백 뒤에도 유지됩니다. 시뮬레이터 검증은 실물 기기·이용권·법률 확인을 대신하지 않습니다.</p><button data-go="safety" class="secondary">중단·복구 작업 열기</button></article></div></section>
<section data-view="catalogs" hidden aria-labelledby="catalog-title"><div class="section-heading"><div><p class="eyebrow">자료 운영</p><h2 id="catalog-title" tabindex="-1">자료·검수</h2></div><button id="catalogs-reload" class="secondary">목록 새로고침</button></div><p>자료를 선택한 뒤 원문 근거, 작성 상태, 검수 기록과 게시 대상을 차례로 확인합니다. 화면 이동과 실패 시 입력은 유지됩니다. 목록·요약은 서버가 반환한 최근 최대 200개 자료 기준입니다.</p>
<div class="split"><div><label>자료 찾기<input id="catalog-search" type="search" placeholder="버전·작성자 검색"></label><div id="catalogs" class="catalog-list"><div class="empty"><h3>자료 목록을 조회해 주세요</h3><p>실제 서버에 등록한 자료만 표시합니다.</p></div></div></div><div class="editor">
<article id="selection"><h3>작업할 자료를 선택해 주세요</h3><p>왼쪽 목록에서 자료를 열거나 아래 고급 입력에서 새 초안을 가져올 수 있습니다.</p></article>
<details id="advanced-input"><summary>고급 입력 · Catalog JSON 가져오기와 편집</summary><label>허가된 Catalog JSON 파일<input id="file" type="file" accept="application/json,.json"></label><label>Catalog JSON<textarea id="catalog" rows="12" spellcheck="false"></textarea></label><div class="actions"><button id="validate" class="secondary">JSON Schema·참조 검사</button><button id="import">새 초안으로 가져오기</button><button id="save" class="secondary">선택 초안 수정 저장</button></div><p>5 MiB 이하 자료만 입력합니다. 수정 저장은 이전 검수 승인을 무효화합니다. 가상·사용자 직접 작성 자료는 공개할 수 없습니다.</p><p id="validation-result" role="status"></p></details>
<details><summary>선택 대상 식별자</summary><label>선택 초안 ID<input id="draft" readonly></label></details>
<div class="workflow-step"><span class="step-number">1</span><div><h3>원문과 이용권 대조</h3><p>아래는 서버 자료에 기입된 URL·문서버전·권리·증거 참조입니다. 비공개 저장소 원본을 실제로 열어 대조해야 합니다. 체크값과 증거 참조만으로 허가를 승인하지 않습니다.</p></div></div><div id="evidence-summary" class="empty">선택한 자료가 없습니다.</div>
<div class="workflow-step"><span class="step-number">2</span><div><h3>다른 사람의 원문 검수 기록</h3><p>AI 검사는 독립 사람 검수가 아닙니다. 작성자와 다른 실제 사람이 원문·금액·순서·조합과 골든 사례를 확인한 뒤 제출합니다.</p></div></div>
<div class="grid"><label>검수자 인증 subject<input id="reviewer" value="reviewer"></label><label>비공개 원문 검수 증거 참조<input id="evidence" placeholder="승인된 비공개 증거 참조"></label></div><label>골든 사례 ID (한 줄에 한 사례)<textarea id="golden" rows="3"></textarea></label><button id="review">입력한 실제 검수 기록 제출</button>
<div class="workflow-step"><span class="step-number">3</span><div><h3>검수 자료 게시</h3><p>선택 자료와 현재 게시 버전을 확인합니다. 서버는 실제 증거·권리·검수와 동시 변경을 다시 검사합니다.</p></div></div><label>예상 현재 게시 releaseId (동시 변경 검사)<input id="expected"></label><button id="publish">선택 검수 자료 게시</button>
<details id="preview-section"><summary>초안 산식 시험 · 미검수</summary><p>모바일과 같은 TypeScript 엔진으로 시험합니다. 시험은 검수나 실제 적용을 승인하지 않으며 중복 조합을 합산하지 않습니다.</p><div class="grid"><label>결제 금액 (원)<input id="amount" type="number" min="1" max="1000000000" step="1" value="12000"></label><label>대상 품목 금액 (비우면 모름)<input id="eligible" type="number" min="0" max="1000000000" step="1"></label><label>브랜드 ID<input id="brand"></label><label>점포 ID (선택)<input id="place"></label><label>채널<select id="channel"><option value="OFFLINE">매장 OFFLINE</option><option value="ONLINE">온라인 ONLINE</option><option value="APP">공식 앱 APP</option></select></label><label>상품 ID (최대 한 카드와 한 멤버십, 쉼표 구분)<input id="products"></label></div><button id="prepare" class="secondary">현재 초안의 조건 입력 준비</button><div id="conditions"></div><button id="preview">입력한 조건으로 산식 시험</button><div id="preview-result" role="status"></div></details>
</div></div></section>
<section data-view="reports" hidden aria-labelledby="reports-title"><div class="section-heading"><div><p class="eyebrow">접수 업무</p><h2 id="reports-title" tabindex="-1">제보함</h2></div><button id="reports-reload" class="secondary">제보 조회</button></div><p>조회·분류·종결·삭제는 감사에 기록됩니다. 종결은 업무 처리 상태이며 혜택 오류가 해결됐다는 뜻이 아닙니다. 본문을 감사·다운로드 파일에 복제하지 않습니다.</p><div class="grid"><label>제보 상태<select id="report-filter"><option value="ALL">모든 상태</option><option value="OPEN">열림</option><option value="CLASSIFIED">분류 완료</option><option value="CLOSED">종결</option></select></label></div><div id="reports"><div class="empty"><h3>제보를 조회해 주세요</h3><p>검수자 권한이 필요합니다. 아직 조회하지 않은 목록을 0건으로 표시하지 않습니다.</p></div></div></section>
<section data-view="safety" hidden aria-labelledby="safety-title"><p class="eyebrow">서비스 보호</p><h2 id="safety-title" tabindex="-1">안전 중단</h2><div id="safety-detail" class="empty">현재 안전 상태를 새로고침해 주세요.</div>
<article><h3>차단과 기능 중지</h3><p>공개 가능한 사유와 대상만 입력합니다. 독립 journal 기록이 확인된 뒤 서버에 반영됩니다. 이 화면에는 기능 ON 전환이 없습니다.</p><div class="grid"><label>차단 rule ID (쉼표 구분)<input id="blocked-rules"></label><label>차단 source ID (쉼표 구분)<input id="blocked-sources"></label></div><label>공개 가능한 중지 사유<input id="reason" maxlength="500"></label><fieldset id="flags"><legend>중지할 기능</legend><label><input type="checkbox" value="catalog">공개 계산 OFF</label><label><input type="checkbox" value="foregroundLocation">전경 위치 OFF</label><label><input type="checkbox" value="iosBackground">iOS 배경 OFF</label><label><input type="checkbox" value="androidBackground">Android 배경 OFF</label><label><input type="checkbox" value="area">지역 안내 OFF</label></fieldset><button id="suspend" class="danger">차단 · 선택 기능 OFF 적용</button><p>법률·자료·실물 기기 증거 없는 공개 자동 기능은 OFF를 유지합니다.</p></article>
<article><h3>이전 버전으로 롤백</h3><p>현재 게시 버전과 호환 가능한 이전 게시 버전을 확인합니다. 새 차단과 기능 OFF는 롤백으로 되돌아가지 않습니다.</p><label>롤백 대상 releaseId<input id="rollback-release" list="published-releases"></label><datalist id="published-releases"></datalist><p id="rollback-current">현재 게시 버전: 확인 필요</p><button id="rollback" class="secondary">이전 호환 버전 활성화</button></article>
<article><h3>DB 복원 뒤 안전 상태 재적용</h3><p>DB 복원·안전 상태 503 때 독립 journal의 삭제·차단 기록을 재적용하고 검증합니다. 실패하면 공개 서비스 보류를 유지하고 기록을 조사해야 합니다. DB와 journal을 함께 과거로 되돌리지 않습니다.</p><button id="replay" class="secondary">독립 journal 복구 재적용·검증</button></article></section>
<section data-view="audit" hidden aria-labelledby="audit-title"><div class="section-heading"><div><p class="eyebrow">변경 추적</p><h2 id="audit-title" tabindex="-1">감사 기록</h2></div><button id="audit-reload" class="secondary">감사 조회</button></div><p>서버가 반환한 수행자·시각·대상·행위만 표시합니다. 최대 최근 500건이며 제보 본문·JWT·삭제 토큰은 포함하지 않습니다.</p><div id="audit" class="empty">감사 기록을 요청해 주세요.</div></section>
</main></div>`;
const field=(id:string)=>document.getElementById(id) as HTMLInputElement;
const val=(id:string)=>field(id).value.trim();
const list=(value:string)=>value.split(',').map(s=>s.trim()).filter(Boolean);
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const text=(id:string,value:string)=>{document.getElementById(id)!.textContent=value;};
const date=(value:string)=>{const time=Date.parse(value);return Number.isFinite(time)?new Date(time).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'시각 확인 필요';};
const label=(value:string)=>({DRAFT:'작성 중',REVIEWED:'검수 기록 등록',PUBLISHED:'게시 이력',OPEN:'열림',CLASSIFIED:'분류 완료',CLOSED:'종결'} as Record<string,string>)[value]??value;
const roleName=(value:string)=>({author:'작성자',reviewer:'검수자',publisher:'게시자'} as Record<string,string>)[value]??value;
const flagsName:Record<string,string>={catalog:'공개 계산',foregroundLocation:'전경 위치',iosBackground:'iOS 배경',androidBackground:'Android 배경',area:'지역 안내'};
field('catalog').value=JSON.stringify(empty,null,2);
function getCatalog(){return validateCatalog(JSON.parse(field('catalog').value));}
let entries:Entry[]=[],inbox:Report[]=[],bootstrap:Bootstrap|null=null,actionRunning=false,editorDirty=false,serverWriteCompleted=false;
const reportDrafts=new Map<string,{category:string;status:string}>();
function go(view:string){document.querySelectorAll<HTMLElement>('[data-view]').forEach(panel=>panel.hidden=panel.dataset.view!==view);document.querySelectorAll<HTMLButtonElement>('nav [data-go]').forEach(button=>{if(button.dataset.go===view)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');});document.querySelector<HTMLElement>(`[data-view="${view}"] h2`)?.focus();}
document.querySelectorAll<HTMLButtonElement>('[data-go]').forEach(button=>button.addEventListener('click',()=>go(button.dataset.go!)));
function authStatus(){text('connection-state',val('jwt')?'운영 JWT · 서버 인증 필요':`로컬 ${roleName(val('subject'))} 시험 · 서버 확인 필요`);}
['base','subject','jwt'].forEach(id=>field(id).addEventListener('change',()=>{authStatus();inbox=[];reportDrafts.clear();text('report-count','조회 전');document.getElementById('reports')!.innerHTML='<div class="empty"><h3>연결·인증이 변경됐습니다</h3><p>이전 제보 본문과 편집 상태를 정리했습니다. 현재 권한으로 다시 조회해 주세요.</p></div>';if(id==='base'){entries=[];bootstrap=null;field('draft').value='';editorDirty=true;text('active','현재 게시 버전: 연결 변경 후 확인 필요');text('checked-at','다른 연결의 이전 조회 결과를 사용하지 않습니다.');text('draft-count','—');text('review-count','—');text('catalog-state','확인 전');text('selection','연결을 변경했습니다. JSON 입력은 유지했으며 현재 서버의 작업 대상은 다시 선택해 주세요.');text('evidence-summary','현재 서버의 자료를 다시 선택해 주세요.');text('safety-summary','연결 변경 후 조회 필요');text('safety-detail','연결 변경 후 조회 필요');field('expected').value='';text('rollback-current','현재 게시 버전: 연결 변경 후 확인 필요');renderCatalogs();text('draft-count','—');text('review-count','—');}text('status','연결 또는 역할을 변경했습니다. 현재 자료·필요한 제보를 새로고침해 주세요.');}));
async function api(path:string,method='GET',body?:unknown){
  const base=new URL(val('base'));if(base.username||base.password||base.pathname!=='/'||base.search||base.hash||!['https:','http:'].includes(base.protocol)||(base.protocol==='http:'&&!['127.0.0.1','localhost','[::1]'].includes(base.hostname)))throw Error('관리 API의 origin 주소를 입력해 주세요. 운영은 HTTPS, 로컬 시험은 loopback HTTP만 허용합니다.');
  const jwt=val('jwt');const required=path.startsWith('/v1/admin/reports')?'reviewer':path==='/v1/admin/import'||method==='PATCH'&&path.startsWith('/v1/admin/catalogs/')?'author':path.endsWith('/review')?'reviewer':path.endsWith('/publish')||['/v1/admin/rollback','/v1/admin/suspensions','/v1/admin/recovery/replay'].includes(path)?'publisher':null;
  if(required)ensureLocalRole(jwt,val('subject'),required);
  const headers:Record<string,string>={'Content-Type':'application/json'};if(jwt)headers.Authorization='Bearer '+jwt;else headers['X-Local-Subject']=val('subject');
  const response=await fetch(base.origin+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000)});
  if(!response.ok){const error=await response.json().catch(()=>({code:'REQUEST_FAILED'}));throw Error(operationError(response.status,typeof error.code==='string'?error.code:'REQUEST_FAILED'));}if(method!=='GET')serverWriteCompleted=true;return response.status===204?null:response.json();
}
async function run(action:()=>Promise<void|boolean>,name:string){if(actionRunning)return;actionRunning=true;serverWriteCompleted=false;const status=document.getElementById('status')!;status.classList.remove('error');status.setAttribute('aria-busy','true');document.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=true);text('status',name+' · 처리 중입니다.');try{const result=await action();text('status',name+(result===false?' · 취소했습니다.':' · 완료했습니다.'));}catch(error){text('status',name+' · '+(serverWriteCompleted?'변경 요청은 서버에서 수락됐지만 후속 조회를 완료하지 못했습니다. 현재 상태를 새로고침해 주세요. ':'')+(error instanceof Error?error.message:'요청을 완료하지 못했습니다.'));status.classList.add('error');}finally{actionRunning=false;status.setAttribute('aria-busy','false');document.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=false);}}
function on(id:string,action:()=>Promise<void|boolean>){const button=document.getElementById(id)!;button.addEventListener('click',()=>void run(action,button.textContent??'관리 작업'));}
function renderCatalogs(){
  const query=val('catalog-search').toLocaleLowerCase();const filtered=entries.filter(e=>(e.releaseId+' '+e.author).toLocaleLowerCase().includes(query));
  document.getElementById('catalogs')!.innerHTML=filtered.length?filtered.map(e=>`<article class="catalog-row ${e.id===val('draft')?'selected':''}"><h3>${esc(e.releaseId)}</h3><span class="badge">${esc(label(e.status))}</span><p>작성 ${esc(e.author)} · ${esc(date(e.createdAt))}</p><p>소스 ${e.catalog.sources.length}개 · 규칙 ${e.catalog.rules.length}개</p><button class="secondary" data-entry="${esc(e.id)}">이 자료 편집기에 열기</button></article>`).join(''):`<div class="empty"><h3>${entries.length?'검색 결과가 없습니다':'등록한 자료가 없습니다'}</h3><p>${entries.length?'버전이나 작성자 검색어를 바꿔 주세요.':'허가된 자료를 고급 입력에서 새 초안으로 가져올 수 있습니다.'}</p></div>`;
  document.querySelectorAll<HTMLButtonElement>('[data-entry]').forEach(button=>button.addEventListener('click',()=>{if(editorDirty&&!window.confirm('저장하지 않은 JSON 편집 내용이 있습니다. 선택한 자료로 바꿀까요?'))return;selectEntry(entries.find(e=>e.id===button.dataset.entry)!);}));
  text('draft-count',String(entries.filter(e=>e.status==='DRAFT').length));text('review-count',String(entries.filter(e=>e.status==='REVIEWED').length));document.getElementById('published-releases')!.innerHTML=entries.filter(e=>e.status==='PUBLISHED').map(e=>`<option value="${esc(e.releaseId)}"></option>`).join('');
}
function renderSelection(){
  const entry=entries.find(e=>e.id===val('draft'));if(!entry)return;
  document.getElementById('selection')!.innerHTML=`<p class="eyebrow">선택한 작업 대상</p><h3>${esc(entry.releaseId)}</h3><span class="badge">${esc(label(entry.status))}</span><p>작성자 ${esc(entry.author)} · 규칙 ${entry.catalog.rules.length}개 · ${entry.catalog.sources.length?'이용권·원문 증거 대조 필요':'등록된 소스 없음'}</p>${entry.status==='PUBLISHED'?'<p class="warning">게시된 자료는 불변입니다. 변경은 새 releaseId의 초안으로 가져오세요.</p>':'<p>수정 저장하면 이전 검수 기록이 무효가 됩니다.</p>'}${entry.review?`<p>등록된 검수자: ${esc(entry.review.reviewer)} · ${esc(date(entry.review.reviewedAt))}</p><p>검수 증거 참조: <code>${esc(entry.review.evidenceRef)}</code></p><p>골든 사례: ${esc(entry.review.goldenTests.join(' · '))}</p>`:'<p class="warning">등록된 실제 원문 검수 기록이 없습니다.</p>'}`;
  const rightNames:Record<string,string>={display:'표시',transform:'변환',iosDistribution:'iOS JSON 배포',androidDistribution:'Android JSON 배포',offlineCache:'오프라인 보존',update:'갱신',revoke:'철회'};
  document.getElementById('evidence-summary')!.innerHTML=entry.catalog.sources.length?entry.catalog.sources.map(s=>{const url=new URL(s.url);const safe=url.protocol==='https:'&&!url.username&&!url.password;return `<article><h4>소스 ${esc(s.id)}</h4><p>${safe?`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">원문 링크 열기</a>`:'원문 URL 확인 필요'} · 문서버전 ${esc(s.documentVersion)}</p><p>원문 확인 ${esc(date(s.checkedAt))}<br>원문 기한 ${esc(date(s.freshUntil))}<br>이용권 기한 ${esc(date(s.rightsUntil))}</p><ul class="rights">${Object.entries(rightNames).map(([key,name])=>`<li>${name}: <strong>${s.rights[key as keyof typeof s.rights]===true?'허용으로 기입':'미확인/허용 없음'}</strong></li>`).join('')}</ul><p>이용권 증거 참조: <code>${esc(s.rights.evidenceRef)}</code></p></article>`;}).join(''):'<p>소스가 없는 자료입니다. 실제 공개 혜택·이용권 증거가 확인됐다는 뜻이 아닙니다.</p>';
}
function selectEntry(entry:Entry){field('catalog').value=JSON.stringify(entry.catalog,null,2);field('draft').value=entry.id;editorDirty=false;document.getElementById('conditions')!.innerHTML='';text('preview-result','');text('validation-result','');renderCatalogs();renderSelection();text('status','자료를 선택했습니다. 입력한 변경은 수정 저장으로 제출하세요.');document.getElementById('selection')!.scrollIntoView({block:'nearest'});}
field('catalog').addEventListener('input',()=>{editorDirty=true;text('validation-result','편집 중 · 저장하면 기존 검수 기록이 무효가 됩니다.');document.getElementById('conditions')!.innerHTML='';text('preview-result','');});
field('catalog-search').addEventListener('input',renderCatalogs);
async function catalogs(){const result=await api('/v1/admin/catalogs');if(!Array.isArray(result))throw Error('자료 목록 응답 형식이 다릅니다.');entries=result;renderCatalogs();renderSelection();}
function renderSafety(){if(!bootstrap)return;const safety=bootstrap.safety;const rows=Object.entries(safety.flags).map(([key,value])=>`<li>${esc(flagsName[key]??key)} <strong>${value?'ON':'OFF'}</strong></li>`).join('');document.getElementById('safety-summary')!.innerHTML=`<ul class="flags-summary">${rows}</ul>`;document.getElementById('safety-detail')!.innerHTML=`<h3>서버에서 확인한 현재 상태</h3><p>게시 버전 <strong>${esc(bootstrap.releaseId)}</strong> · 안전 revision ${safety.revision}</p><ul class="flags-summary">${rows}</ul><p>차단 규칙 ${safety.blockedRuleIds.length}개 · 차단 소스 ${safety.blockedSourceIds.length}개</p><details><summary>현재 차단 대상 보기</summary><p>규칙: ${esc(safety.blockedRuleIds.join(', ')||'없음')}</p><p>소스: ${esc(safety.blockedSourceIds.join(', ')||'없음')}</p></details>`;text('catalog-state',safety.flags.catalog?'ON':'OFF');}
async function active(){bootstrap=await api('/v1/bootstrap');field('expected').value=bootstrap!.releaseId;text('active','현재 게시 버전: '+bootstrap!.releaseId+' · 안전 revision '+bootstrap!.safety.revision);text('rollback-current','현재 게시 버전: '+bootstrap!.releaseId);text('checked-at','마지막 조회: '+date(new Date().toISOString())+' · 서울 시각');authStatus();renderSafety();}
async function reload(){await active();await catalogs();}
on('reload',reload);on('dashboard-reload',reload);on('catalogs-reload',catalogs);
field('file').addEventListener('change',()=>void run(async()=>{const file=field('file').files?.[0];if(!file)return;if(file.size>5*1024*1024)throw Error('5 MiB 이하 JSON 파일만 입력할 수 있습니다.');const raw=await file.text();validateCatalog(JSON.parse(raw));if(editorDirty&&!window.confirm('저장하지 않은 편집 내용을 가져온 파일로 바꿀까요?'))return;field('catalog').value=raw;field('draft').value='';editorDirty=true;text('validation-result','파일을 불러왔습니다. 새 초안으로 가져오면 서버에 등록됩니다.');text('selection','아직 서버에 등록하지 않은 새 입력입니다. 새 초안으로 가져오기를 실행해 주세요.');text('evidence-summary','서버 초안을 등록·선택한 뒤 원문과 이용권을 대조합니다.');},'Catalog 파일 불러오기'));
on('validate',async()=>{const c=getCatalog();text('validation-result',`형식·참조 검사 통과: ${c.rules.length}개 규칙. 이용권·실제 사람 검수·게시 승인과는 별도입니다.`);});
on('import',async()=>{const result=await api('/v1/admin/import','POST',getCatalog());field('draft').value=result.id;editorDirty=false;await catalogs();});
on('save',async()=>{if(!val('draft'))throw Error('수정할 자료를 목록에서 선택해 주세요.');await api('/v1/admin/catalogs/'+encodeURIComponent(val('draft')),'PATCH',getCatalog());editorDirty=false;await catalogs();});
on('review',async()=>{const selected=entries.find(e=>e.id===val('draft'));if(!selected)throw Error('실제 서버 자료를 목록에서 선택해 주세요.');if(editorDirty)throw Error('저장하지 않은 편집 내용이 있습니다. 수정 저장 후 원문 검수를 진행해 주세요.');await api('/v1/admin/catalogs/'+encodeURIComponent(selected.id)+'/review','POST',reviewInput(selected.author,val('reviewer'),val('evidence'),field('golden').value));await catalogs();});
on('prepare',async()=>{const c=getCatalog();field('brand').value=c.brands[0]?.id??'';field('place').value=c.places[0]?.id??'';field('products').value=c.products.filter((p,i,arr)=>arr.findIndex(x=>x.kind===p.kind)===i).map(p=>p.id).join(',');document.getElementById('conditions')!.innerHTML=c.rules.length?c.rules.map(r=>`<article><h3>${esc(r.title)}</h3><p>혜택 버전 ${esc(r.version)} · 기준월 ${kstMonth(Date.now())}</p>${r.requiredConditions.map(key=>`<label>${esc(conditionLabel(key))}<select data-rule="${esc(r.id)}" data-condition="${esc(key)}"><option value="UNKNOWN">모름</option><option value="TRUE">충족</option><option value="FALSE">미충족</option></select></label>`).join('')}${r.remainingWonRequired?`<label>잔여 할인 한도 (원, 비우면 모름)<input type="number" min="0" max="1000000000" step="1" data-remaining-won="${esc(r.id)}"></label>`:''}${r.remainingUsesRequired?`<label>잔여 이용 횟수 (비우면 모름)<input type="number" min="0" step="1" data-remaining-uses="${esc(r.id)}"></label>`:''}</article>`).join(''):'<p>시험할 계산 규칙이 없습니다.</p>';});
const optionalNumber=(input:HTMLInputElement|undefined)=>input?.value.trim()?Number(input.value):null;
on('preview',async()=>{const catalog=getCatalog();const now=Date.now();const conditions:Record<string,RuleConditions>={};for(const r of catalog.rules){const values:RuleConditions['values']={};for(const select of Array.from(document.querySelectorAll<HTMLSelectElement>('[data-condition]')))if(select.dataset.rule===r.id)values[select.dataset.condition!]={value:select.value as Truth,checkedAt:new Date(now).toISOString(),month:kstMonth(now),ruleVersion:r.version};const won=Array.from(document.querySelectorAll<HTMLInputElement>('[data-remaining-won]')).find(x=>x.dataset.remainingWon===r.id);const uses=Array.from(document.querySelectorAll<HTMLInputElement>('[data-remaining-uses]')).find(x=>x.dataset.remainingUses===r.id);conditions[r.id]={values,remainingWon:optionalNumber(won),remainingUses:optionalNumber(uses),month:kstMonth(now),ruleVersion:r.version};}
  const amount=Number(val('amount'));if(!Number.isSafeInteger(amount)||amount<=0)throw Error('원 단위 양의 정수를 입력해 주세요.');const eligible=val('eligible');const result=previewDraft({amountWon:amount,...(eligible?{eligibleAmountWon:Number(eligible)}:{}),brandId:val('brand'),placeId:val('place'),channel:val('channel'),productIds:list(val('products')),catalog,conditions,now,mode:'PERSONAL'});
  document.getElementById('preview-result')!.innerHTML=`<h3>초안 개인 시나리오 · 미검수 · 중복 합산 없음</h3>${result.best?`<dl><dt>즉시 할인 예상</dt><dd>${result.best.instantWon.toLocaleString('ko-KR')}원</dd><dt>지금 결제액 예상</dt><dd>${result.best.payableWon.toLocaleString('ko-KR')}원</dd><dt>청구 할인 예상</dt><dd>${result.best.billingWon.toLocaleString('ko-KR')}원</dd></dl>`:'<p>조건 모름·미충족 때문에 예상 숫자를 표시하지 않습니다.</p>'}${result.results.map(r=>`<p>${esc(catalog.rules.find(rule=>rule.id===r.ruleId)?.title)}: ${esc(({TRUE:'입력 조건 충족',FALSE:'미충족',UNKNOWN:'확인 필요'} as Record<string,string>)[r.eligibility])} ${r.reasons.map(reason=>esc(reasonText(reason))).join(' · ')}</p>`).join('')}`;
});
['amount','eligible','brand','place','channel','products'].forEach(id=>field(id).addEventListener('input',()=>text('preview-result','입력이 바뀌었습니다. 산식 시험을 다시 실행해 주세요.')));
document.getElementById('conditions')!.addEventListener('input',()=>text('preview-result','조건이 바뀌었습니다. 산식 시험을 다시 실행해 주세요.'));
on('publish',async()=>{if(!val('draft')||!val('expected'))throw Error('선택 자료와 예상 현재 게시 버전을 확인해 주세요.');if(editorDirty)throw Error('저장하지 않은 편집 내용이 있습니다. 수정 저장·재검수 후 게시해 주세요.');if(!window.confirm('선택한 자료를 공개 게시할까요? 실제 이용권·원문 검수·현재 게시 버전을 확인해 주세요.'))return false;await api('/v1/admin/catalogs/'+encodeURIComponent(val('draft'))+'/publish','POST',{expectedReleaseId:val('expected')});await active();await catalogs();});
on('rollback',async()=>{if(!val('rollback-release')||!val('expected'))throw Error('롤백 대상과 예상 현재 게시 버전을 확인해 주세요.');if(!window.confirm('선택한 이전 버전을 활성화할까요? 최신 차단과 OFF는 유지됩니다.'))return false;await api('/v1/admin/rollback','POST',{releaseId:val('rollback-release'),expectedReleaseId:val('expected')});await active();});
on('suspend',async()=>{if(!val('reason'))throw Error('중지 사유를 입력해 주세요.');const flags=Object.fromEntries(Array.from(document.querySelectorAll<HTMLInputElement>('#flags input:checked')).map(x=>[x.value,false]));const ruleIds=list(val('blocked-rules')),sourceIds=list(val('blocked-sources'));if(!ruleIds.length&&!sourceIds.length&&!Object.keys(flags).length)throw Error('차단 대상 또는 중지 기능을 선택해 주세요.');if(!window.confirm(`규칙 ${ruleIds.length}개·소스 ${sourceIds.length}개 차단, 기능 ${Object.keys(flags).length}개 OFF를 적용할까요?`))return false;await api('/v1/admin/suspensions','POST',{ruleIds,sourceIds,flags,reason:val('reason')});await active();});
on('replay',async()=>{await api('/v1/admin/recovery/replay','POST',{});await active();});
function renderReports(){const filter=val('report-filter');const filtered=inbox.filter(r=>filter==='ALL'||r.status===filter);text('report-count',String(inbox.filter(r=>r.status!=='CLOSED').length));document.getElementById('reports')!.innerHTML=filtered.length?filtered.map(r=>{const editing=reportDrafts.get(r.id)??r;return `<article data-report="${esc(r.id)}"><div class="section-heading"><h3>제보 ${esc(r.id)}</h3><span class="badge">${esc(label(r.status))}</span></div><p>${esc(date(r.createdAt))} · 규칙 ${esc(r.ruleId??'미지정')}</p><details><summary>제보 본문 보기 · 개인정보 주의</summary><p class="report-message">${esc(r.message)}</p></details><div class="grid"><label>분류<input class="report-category" value="${esc(editing.category)}" maxlength="80"></label><label>처리 상태<select class="report-status">${['OPEN','CLASSIFIED','CLOSED'].map(status=>`<option value="${status}" ${status===editing.status?'selected':''}>${label(status)}</option>`).join('')}</select></label></div><p class="muted">종결은 실제 혜택 오류의 해결 확인을 뜻하지 않습니다.</p><div class="actions"><button class="secondary" data-report-save="${esc(r.id)}">분류·상태 저장</button><button class="danger" data-report-delete="${esc(r.id)}">서버 제보 삭제</button></div>${reportDrafts.has(r.id)?'<p class="warning">저장하지 않은 분류·상태 변경이 있습니다.</p>':''}</article>`;}).join(''):`<div class="empty"><h3>${inbox.length?'선택한 상태의 제보가 없습니다':'접수된 제보가 없습니다'}</h3><p>실제 조회한 목록 기준입니다.</p></div>`;
  document.querySelectorAll<HTMLButtonElement>('[data-report-save]').forEach(button=>button.addEventListener('click',()=>void run(async()=>{const article=button.closest('article')!;const category=(article.querySelector('.report-category') as HTMLInputElement).value,status=(article.querySelector('.report-status') as HTMLSelectElement).value;await api('/v1/admin/reports/'+encodeURIComponent(button.dataset.reportSave!),'PATCH',reportUpdateInput(category,status));reportDrafts.delete(button.dataset.reportSave!);await reports();},'제보 분류·상태 저장')));
  document.querySelectorAll<HTMLButtonElement>('[data-report-delete]').forEach(button=>button.addEventListener('click',()=>void run(async()=>{if(!window.confirm('이 서버 제보를 삭제할까요? 독립 삭제 journal을 먼저 기록하며 본문은 복원하지 않습니다.'))return false;await api('/v1/admin/reports/'+encodeURIComponent(button.dataset.reportDelete!),'DELETE');reportDrafts.delete(button.dataset.reportDelete!);await reports();},'서버 제보 삭제')));
}
field('report-filter').addEventListener('change',renderReports);
document.getElementById('reports')!.addEventListener('input',event=>{const article=(event.target as HTMLElement).closest<HTMLElement>('[data-report]');if(!article)return;const category=(article.querySelector('.report-category') as HTMLInputElement).value,status=(article.querySelector('.report-status') as HTMLSelectElement).value;reportDrafts.set(article.dataset.report!,{category,status});});
async function reports(){const result=await api('/v1/admin/reports');if(!Array.isArray(result))throw Error('제보 목록 응답 형식이 다릅니다.');inbox=result;renderReports();}
on('reports-reload',reports);
on('audit-reload',async()=>{const rows:Audit[]=await api('/v1/admin/audit');if(!Array.isArray(rows))throw Error('감사 목록 응답 형식이 다릅니다.');document.getElementById('audit')!.innerHTML=rows.length?`<div class="table-scroll" tabindex="0" aria-label="최근 감사 기록"><table><thead><tr><th scope="col">시각 (서울)</th><th scope="col">수행자</th><th scope="col">행위</th><th scope="col">대상</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${esc(date(row.createdAt))}</td><td>${esc(row.actor)}</td><td>${esc(row.action)}</td><td>${esc(row.target)}</td></tr>`).join('')}</tbody></table></div>`:'<p>조회한 감사 기록이 없습니다.</p>';});
