import './style.css';
import {validateCatalog,kstMonth} from '../../../packages/benefit-core/src/index.ts';
import type {Catalog,RuleConditions,Truth} from '../../../contracts/types.ts';
import {previewDraft} from './preview.ts';
import empty from '../../../contracts/empty-catalog.json';
import {reasonText} from '../../mobile/src/model.ts';
const logo = new URL('../../../assets/brand/logo.svg',import.meta.url).href;
interface Entry {id:string;releaseId:string;status:string;author:string;createdAt:string;catalog:Catalog;review:unknown}
interface Report {id:string;ruleId?:string;category:string;message:string;status:string;createdAt:string}
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<header><img src="${logo}" alt="혜택패스"><div><h1>자료 관리</h1><p>검증판 · 공개 자료는 이용권과 실제 독립 원문 검수가 확인된 범위만</p></div></header>
<main><section><h2>API 연결과 권한</h2><div class="grid"><label>API 주소<input id="base" value="http://127.0.0.1:8080"></label><label>개발 권한 시험<select id="subject"><option value="author">작성자 author</option><option value="reviewer">검수자 reviewer</option><option value="publisher">게시자 publisher</option></select></label><label>운영 Bearer JWT (선택, 이 페이지 메모리에만 보관)<input id="jwt" type="password" autocomplete="off"></label></div><p>개발 X-Local-Subject는 loopback 서버의 권한 시험용입니다. 실제 사람의 인증·원문 검수 증거를 뜻하지 않습니다. 운영에서는 서버 OIDC/MFA와 권한 확인을 통과한 JWT가 필요합니다.</p><button id="reload">현재 자료와 inbox 새로고침</button><p id="active">현재 게시 버전: 확인 필요</p></section>
<p id="status" role="status" aria-live="polite"></p>
<nav aria-label="관리 작업"><a href="#catalog-section">자료 입력·검수</a><a href="#preview-section">산식 시험</a><a href="#safety-section">게시·안전</a><a href="#inbox-section">제보 inbox</a><a href="#audit-section">감사</a></nav>
<section id="catalog-section"><h2>자료 입력·편집과 형식 검사</h2><label>허가된 Catalog JSON 파일<input id="file" type="file" accept="application/json,.json"></label><label>Catalog JSON<textarea id="catalog" rows="15" spellcheck="false"></textarea></label><div class="actions"><button id="validate">JSON Schema·참조 검사</button><button id="import">새 초안으로 가져오기</button><button id="save" class="secondary">선택 초안 수정 저장</button></div><p>초안이 변경되면 검수 승인은 무효가 됩니다. 가상 자료와 사용자 직접 작성 규칙은 공개할 수 없습니다.</p><div id="catalogs"></div><label>선택 초안 ID<input id="draft"></label><h3>실제 원문 검수 기록</h3><div class="grid"><label>검수자 인증 subject<input id="reviewer" value="reviewer"></label><label>비공개 원문 검수 증거 참조<input id="evidence" placeholder="EVIDENCE_DIR 안의 승인 근거"></label></div><label>골든 사례 ID (한 줄에 한 사례)<textarea id="golden" rows="3"></textarea></label><p>검수자는 작성자와 달라야 합니다. 실제 사람이 원문·이용권·금액·순서·조합을 확인한 증거가 없는 기록은 등록하지 마세요. AI 검사는 독립 사람 검수가 아닙니다.</p><button id="review">입력한 실제 검수 기록 제출</button></section>
<section id="preview-section"><h2>초안 산식 시험 · 미검수</h2><p>같은 TypeScript 엔진으로 개인 시나리오를 시험합니다. 초안의 검수 상태를 승인하지 않으며 중복 조합은 이 시험에서 합산하지 않습니다.</p><div class="grid"><label>결제 금액 (원)<input id="amount" type="number" min="1" max="1000000000" step="1" value="12000"></label><label>대상 품목 금액 (비우면 모름)<input id="eligible" type="number" min="0" max="1000000000" step="1"></label><label>브랜드 ID<input id="brand"></label><label>점포 ID (선택)<input id="place"></label><label>채널<input id="channel" value="OFFLINE"></label><label>상품 ID (최대 한 카드와 한 멤버십, 쉼표 구분)<input id="products"></label></div><button id="prepare" class="secondary">현재 초안의 조건 입력 준비</button><div id="conditions"></div><button id="preview">입력한 조건으로 산식 시험</button><div id="preview-result" role="status"></div></section>
<section id="safety-section"><h2>버전 게시·롤백·긴급 차단</h2><label>예상 현재 게시 releaseId (동시 변경 검사)<input id="expected"></label><button id="publish">선택 검수 자료 게시</button><label>롤백 대상 releaseId<input id="rollback-release"></label><button id="rollback" class="secondary">이전 호환 버전 활성화</button><p>롤백은 최신 차단 overlay를 유지합니다.</p><h3>차단과 기능 중지</h3><div class="grid"><label>차단 rule ID (쉼표 구분)<input id="blocked-rules"></label><label>차단 source ID (쉼표 구분)<input id="blocked-sources"></label></div><label>공개 가능한 중지 사유<input id="reason" maxlength="500"></label><div id="flags"><label><input type="checkbox" value="catalog">공개 계산 OFF</label><label><input type="checkbox" value="foregroundLocation">전경 위치 OFF</label><label><input type="checkbox" value="iosBackground">iOS 배경 OFF</label><label><input type="checkbox" value="androidBackground">Android 배경 OFF</label><label><input type="checkbox" value="area">지역 안내 OFF</label></div><button id="suspend" class="danger">차단 · 선택 기능 OFF 적용</button><p>법률·자료·실기기 증거 없는 배경 기능은 기본 OFF입니다. 이 화면은 이를 임의 활성화하지 않습니다.</p><button id="replay" class="secondary">독립 journal 복구 재적용·검증</button></section>
<section id="inbox-section"><h2>제보 inbox</h2><p>개인정보가 포함될 수 있습니다. 조회·분류·종결·삭제는 서버 감사에 기록되며 본문을 감사에 복제하지 않습니다.</p><button id="reports-reload" class="secondary">제보 조회</button><div id="reports"></div></section>
<section id="audit-section"><h2>관리 감사</h2><button id="audit-reload" class="secondary">감사 조회</button><pre id="audit" tabindex="0">감사 기록을 요청해 주세요.</pre></section></main>`;
const field=(id:string)=>document.getElementById(id) as HTMLInputElement;
const val=(id:string)=>field(id).value.trim();
const list=(value:string)=>value.split(',').map(s=>s.trim()).filter(Boolean);
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const text=(id:string,value:string)=>{document.getElementById(id)!.textContent=value;};
field('catalog').value=JSON.stringify(empty,null,2);
function getCatalog(){return validateCatalog(JSON.parse(field('catalog').value));}
let entries:Entry[]=[];
let actionRunning=false;
async function api(path:string,method='GET',body?:unknown){
  const base=new URL(val('base'));if(base.username||base.password||!['https:','http:'].includes(base.protocol)||(base.protocol==='http:'&&!['127.0.0.1','localhost','[::1]'].includes(base.hostname)))throw Error('운영 관리 API는 HTTPS를 사용해 주세요.');
  const jwt=val('jwt');const headers:Record<string,string>={'Content-Type':'application/json'};if(jwt)headers.Authorization='Bearer '+jwt;else headers['X-Local-Subject']=val('subject');
  const response=await fetch(base.origin+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000)});
  if(!response.ok){const error=await response.json().catch(()=>({message:'응답을 확인하지 못했습니다.'}));throw Error(`${response.status}: ${error.message??error.code??'요청 실패'}`);}return response.status===204?null:response.json();
}
async function run(action:()=>Promise<void>){if(actionRunning)return;actionRunning=true;document.getElementById('status')!.classList.remove('error');document.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=true);text('status','요청을 처리하고 있습니다.');try{await action();text('status','요청을 완료했습니다. 실제 서버 응답을 반영했습니다.');}catch(error){text('status',error instanceof Error?error.message:'요청 실패');document.getElementById('status')!.classList.add('error');}finally{actionRunning=false;document.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=false);}}
function on(id:string,action:()=>Promise<void>){document.getElementById(id)!.addEventListener('click',()=>void run(action));}
async function catalogs(){entries=await api('/v1/admin/catalogs');if(!Array.isArray(entries))throw Error('카탈로그 목록 형식이 다릅니다.');document.getElementById('catalogs')!.innerHTML=entries.length?entries.map(e=>`<article><h3>${esc(e.releaseId)}</h3><p>${esc(e.status)} · 작성 ${esc(e.author)} · ${esc(e.createdAt)}</p><button class="secondary" data-entry="${esc(e.id)}">이 자료 편집기에 열기</button></article>`).join(''):'<p>등록된 초안이 없습니다. 허가된 자료를 직접 입력해 주세요.</p>';document.querySelectorAll<HTMLButtonElement>('[data-entry]').forEach(button=>button.addEventListener('click',()=>{const e=entries.find(x=>x.id===button.dataset.entry)!;field('catalog').value=JSON.stringify(e.catalog,null,2);field('draft').value=e.id;text('status','선택한 자료를 편집기에 열었습니다. 변경은 저장 버튼으로 제출하세요.');document.getElementById('catalog')!.focus();}));}
async function active(){const b=await api('/v1/bootstrap');field('expected').value=b.releaseId;text('active','현재 게시 버전: '+b.releaseId+' · 안전 revision '+b.safety.revision);}
on('reload',async()=>{await active();await catalogs();});
field('file').addEventListener('change',()=>void run(async()=>{const file=field('file').files?.[0];if(!file)return;if(file.size>5*1024*1024)throw Error('5 MiB 이하 JSON 파일만 입력할 수 있습니다.');const raw=await file.text();validateCatalog(JSON.parse(raw));field('catalog').value=raw;field('draft').value='';}));
on('validate',async()=>{const c=getCatalog();text('preview-result',`형식·참조 검사 통과: ${c.rules.length}개 규칙. 이용권·사람 검수·게시 승인과는 별도입니다.`);});
on('import',async()=>{const c=getCatalog();const result=await api('/v1/admin/import','POST',c);field('draft').value=result.id;await catalogs();});
on('save',async()=>{if(!val('draft'))throw Error('수정할 초안 ID를 선택해 주세요.');await api('/v1/admin/catalogs/'+encodeURIComponent(val('draft')),'PATCH',getCatalog());await catalogs();});
on('review',async()=>{if(!val('draft')||!val('evidence')||!val('reviewer'))throw Error('초안·실제 검수자·증거 참조를 확인해 주세요.');const goldenTests=field('golden').value.split('\n').map(v=>v.trim()).filter(Boolean);if(!goldenTests.length)throw Error('실행한 골든 사례 ID가 필요합니다.');await api('/v1/admin/catalogs/'+encodeURIComponent(val('draft'))+'/review','POST',{reviewer:val('reviewer'),method:'HUMAN_ORIGINAL',evidenceRef:val('evidence'),goldenTests});await catalogs();});
on('prepare',async()=>{const c=getCatalog();field('brand').value=c.brands[0]?.id??'';field('place').value=c.places[0]?.id??'';field('products').value=c.products.filter((p,i,arr)=>arr.findIndex(x=>x.kind===p.kind)===i).map(p=>p.id).join(',');document.getElementById('conditions')!.innerHTML=c.rules.map(r=>`<article><h3>${esc(r.title)}</h3><p>혜택 버전 ${esc(r.version)} · 기준월 ${kstMonth(Date.now())}</p>${r.requiredConditions.map((key,i)=>`<label>${esc(key)}<select data-rule="${esc(r.id)}" data-condition="${esc(key)}"><option value="UNKNOWN">모름</option><option value="TRUE">충족</option><option value="FALSE">미충족</option></select></label>`).join('')}${r.remainingWonRequired?`<label>잔여 할인 한도 (원, 비우면 모름)<input type="number" min="0" max="1000000000" step="1" data-remaining-won="${esc(r.id)}"></label>`:''}${r.remainingUsesRequired?`<label>잔여 이용 횟수 (비우면 모름)<input type="number" min="0" step="1" data-remaining-uses="${esc(r.id)}"></label>`:''}</article>`).join('');});
const optionalNumber=(input:HTMLInputElement|undefined)=>input?.value.trim()?Number(input.value):null;
on('preview',async()=>{const catalog=getCatalog();const now=Date.now();const conditions:Record<string,RuleConditions>={};for(const r of catalog.rules){const values:RuleConditions['values']={};for(const select of Array.from(document.querySelectorAll<HTMLSelectElement>('[data-condition]')))if(select.dataset.rule===r.id)values[select.dataset.condition!]={value:select.value as Truth,checkedAt:new Date(now).toISOString(),month:kstMonth(now),ruleVersion:r.version};const won=Array.from(document.querySelectorAll<HTMLInputElement>('[data-remaining-won]')).find(x=>x.dataset.remainingWon===r.id);const uses=Array.from(document.querySelectorAll<HTMLInputElement>('[data-remaining-uses]')).find(x=>x.dataset.remainingUses===r.id);conditions[r.id]={values,remainingWon:optionalNumber(won),remainingUses:optionalNumber(uses),month:kstMonth(now),ruleVersion:r.version};}
  const amount=Number(val('amount'));if(!Number.isSafeInteger(amount)||amount<=0)throw Error('원 단위 양의 정수를 입력해 주세요.');const eligible=val('eligible');const result=previewDraft({amountWon:amount,...(eligible?{eligibleAmountWon:Number(eligible)}:{}),brandId:val('brand'),placeId:val('place'),channel:val('channel'),productIds:list(val('products')),catalog,conditions,now,mode:'PERSONAL'});
  document.getElementById('preview-result')!.innerHTML=`<h3>초안 개인 시나리오 · 미검수 · 중복 합산 없음</h3>${result.best?`<dl><dt>즉시 할인 예상</dt><dd>${result.best.instantWon.toLocaleString('ko-KR')}원</dd><dt>지금 결제액 예상</dt><dd>${result.best.payableWon.toLocaleString('ko-KR')}원</dd><dt>청구 할인 예상</dt><dd>${result.best.billingWon.toLocaleString('ko-KR')}원</dd></dl>`:'<p>조건 모름·미충족 때문에 예상 숫자를 표시하지 않습니다.</p>'}${result.results.map(r=>`<p>${esc(catalog.rules.find(rule=>rule.id===r.ruleId)?.title)}: ${esc(r.eligibility)} ${r.reasons.map(reason=>esc(reasonText(reason))).join(' · ')}</p>`).join('')}`;
});
on('publish',async()=>{if(!val('draft')||!val('expected'))throw Error('선택 자료와 예상 현재 게시 버전을 확인해 주세요.');await api('/v1/admin/catalogs/'+encodeURIComponent(val('draft'))+'/publish','POST',{expectedReleaseId:val('expected')});await active();await catalogs();});
on('rollback',async()=>{if(!val('rollback-release')||!val('expected'))throw Error('롤백 대상과 예상 현재 게시 버전을 확인해 주세요.');await api('/v1/admin/rollback','POST',{releaseId:val('rollback-release'),expectedReleaseId:val('expected')});await active();});
on('suspend',async()=>{if(!val('reason'))throw Error('중지 사유를 입력해 주세요.');const flags=Object.fromEntries(Array.from(document.querySelectorAll<HTMLInputElement>('#flags input:checked')).map(x=>[x.value,false]));const ruleIds=list(val('blocked-rules')),sourceIds=list(val('blocked-sources'));if(!ruleIds.length&&!sourceIds.length&&!Object.keys(flags).length)throw Error('차단 대상 또는 중지 기능을 선택해 주세요.');await api('/v1/admin/suspensions','POST',{ruleIds,sourceIds,flags,reason:val('reason')});await active();});
on('replay',async()=>{await api('/v1/admin/recovery/replay','POST',{});await active();});
async function reports(){const inbox:Report[]=await api('/v1/admin/reports');if(!Array.isArray(inbox))throw Error('inbox 응답 형식이 다릅니다.');document.getElementById('reports')!.innerHTML=inbox.length?inbox.map(r=>`<article data-report="${esc(r.id)}"><h3>제보 ${esc(r.id)}</h3><p>${esc(r.createdAt)} · 규칙 ${esc(r.ruleId??'미지정')} · ${esc(r.status)}</p><p class="report-message">${esc(r.message)}</p><label>분류<input class="report-category" value="${esc(r.category)}" maxlength="100"></label><label>상태<select class="report-status"><option value="CLASSIFIED">분류 완료</option><option value="CLOSED">종결</option><option value="OPEN">열림</option></select></label><div class="actions"><button class="secondary" data-report-save="${esc(r.id)}">분류·상태 저장</button><button class="danger" data-report-delete="${esc(r.id)}">서버 제보 삭제</button></div></article>`).join(''):'<p>접수된 제보가 없습니다.</p>';
  document.querySelectorAll<HTMLButtonElement>('[data-report-save]').forEach(button=>button.addEventListener('click',()=>void run(async()=>{const article=button.closest('article')!;const category=(article.querySelector('.report-category') as HTMLInputElement).value.trim(),status=(article.querySelector('.report-status') as HTMLSelectElement).value;if(!category)throw Error('제보 분류를 입력해 주세요.');await api('/v1/admin/reports/'+encodeURIComponent(button.dataset.reportSave!),'PATCH',{category,status});await reports();})));
  document.querySelectorAll<HTMLButtonElement>('[data-report-delete]').forEach(button=>button.addEventListener('click',()=>void run(async()=>{if(!window.confirm('이 서버 제보를 삭제할까요? 삭제 journal을 먼저 기록하며 본문은 복원하지 않습니다.'))return;await api('/v1/admin/reports/'+encodeURIComponent(button.dataset.reportDelete!),'DELETE');await reports();})));
}
on('reports-reload',reports);on('audit-reload',async()=>{text('audit',JSON.stringify(await api('/v1/admin/audit'),null,2));});
